import json
import datetime
import os

# ---------------------------------------------------------
# MOCK SCRAPER cho Goethe-Zertifikat B1 Modelltest
# Trong thực tế, bạn sẽ dùng requests + BeautifulSoup hoặc pdfplumber 
# để bóc tách dữ liệu từ trang web/pdf.
# Ở đây ta sẽ giả lập dữ liệu bóc tách được.
# ---------------------------------------------------------

def scrape_b1_reading_test():
    print("Scraping Goethe-Zertifikat B1 Modelltest - Lesen Teil 1...")
    
    # Giả lập dữ liệu text đọc hiểu
    reading_text = (
        "Liebe Nachbarn, \n"
        "wie Sie wissen, feiere ich am Samstag meinen Geburtstag. "
        "Die Party findet im Garten statt. Ich hoffe, dass das Wetter "
        "schön bleibt. Es wird Musik geben, aber ab 22 Uhr werden wir "
        "leiser sein. Bitte entschuldigen Sie den Lärm. "
        "Sie sind natürlich auch herzlich eingeladen! \n"
        "Viele Grüße, Thomas"
    )
    
    # Giả lập các câu hỏi trắc nghiệm Richtig/Falsch
    questions = [
        {
            "id": "q1",
            "type": "TRUE_FALSE",
            "question": "Thomas feiert seinen Geburtstag im Haus.",
            "options": ["Richtig", "Falsch"],
            "correctAnswer": "Falsch",
            "explanation": "Die Party findet im Garten statt."
        },
        {
            "id": "q2",
            "type": "TRUE_FALSE",
            "question": "Thomas lädt auch seine Nachbarn zur Party ein.",
            "options": ["Richtig", "Falsch"],
            "correctAnswer": "Richtig",
            "explanation": "Sie sind natürlich auch herzlich eingeladen!"
        },
        {
            "id": "q3",
            "type": "TRUE_FALSE",
            "question": "Nach 22 Uhr gibt es keine Musik mehr.",
            "options": ["Richtig", "Falsch"],
            "correctAnswer": "Falsch",
            "explanation": "Es wird Musik geben, aber ab 22 Uhr werden wir leiser sein. (Musik noch da, nur leiser)"
        }
    ]
    
    content_data = {
        "title": "Lesen Teil 1: E-Mail lesen",
        "instructions": "Lesen Sie den Text und kreuzen Sie an: Richtig oder Falsch?",
        "readingText": reading_text,
        "questions": questions
    }
    
    return content_data


def generate_sql_migration(content_data):
    file_name = "V113__seed_b1_exam_sample.sql"
    output_dir = "backend/src/main/resources/db/migration"
    
    os.makedirs(output_dir, exist_ok=True)
    file_path = os.path.join(output_dir, file_name)
    
    print(f"Generating SQL file: {file_path}...")
    
    content_json_str = json.dumps(content_data, ensure_ascii=False).replace("'", "''")
    
    sql = f"""-- ============================================================
-- V113: Seed Sample Goethe-Zertifikat B1 Exam Data
-- Generated by python scraper
-- ============================================================

INSERT INTO practice_exercises (
    exercise_type, 
    cefr_level, 
    skill_type, 
    exam_name, 
    content_json, 
    source_name, 
    source_url, 
    xp_reward
) VALUES (
    'EXAM',
    'B1',
    'READING',
    'Goethe-Zertifikat B1 Modellsatz - Lesen',
    '{content_json_str}'::jsonb,
    'Goethe-Institut',
    'https://www.goethe.de/ins/vn/vi/sta/hcm/prf/bar.html',
    100
);
"""
    
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(sql)
        
    print("SQL generation complete!")

if __name__ == "__main__":
    b1_data = scrape_b1_reading_test()
    generate_sql_migration(b1_data)
