import * as React from 'react'
import {
  LayoutDashboard,
  Calendar,
  Clock,
  Users,
  ClipboardCheck,
  LineChart,
  Bell,
  SpellCheck,
  FileText,
  Image as ImageIcon,
  User,
  MessageSquare,
  UserPlus,
  AlertCircle,
  Table,
  Inbox,
  CreditCard,
  Coins,
  Building2,
  Tag,
  BookOpen,
  Images,
  SlidersHorizontal,
  Megaphone,
  Mic,
  MessagesSquare,
  ReceiptText,
  GraduationCap,
  BadgeCheck,
  Landmark,
  Receipt,
  Mail,
  ShieldCheck,
  Settings,
  LogOut,
  ListChecks,
  Presentation,
  Search,
  HelpCircle,
  Circle,
  Compass,
  ChevronDown,
  PenLine,
  FileQuestion,
  TrendingUp,
  ClipboardList,
  Database,
  Repeat,
  PlayCircle,
  Route,
  Trophy,
  Library,
  Gamepad2,
  Newspaper,
  Award,
  History,
  Menu,
  X,
  // — Trạng thái & hành động (thay cho ✅ ❌ ⚠️ 💡 🎉 ✨ 🔒 💾 …)
  Check,
  CircleCheck,
  CircleX,
  TriangleAlert,
  Lightbulb,
  PartyPopper,
  Sparkles,
  ThumbsUp,
  Lock,
  Unlock,
  Save,
  Pencil,
  RefreshCw,
  Volume2,
  Headphones,
  Bot,
  Quote,
  Eye,
  Timer,
  ChartNoAxesCombined,
  UserSearch,
  Target,
  Zap,
  Flame,
  Star,
  Flag,
  // — Chủ đề node lộ trình (bảng tra ở `emojiIconMap.ts`)
  Type,
  Hash,
  Ruler,
  Hand,
  Palette,
  Utensils,
  Stethoscope,
  Bus,
  Monitor,
  Wrench,
  Link as LinkIcon,
  Briefcase,
  Dumbbell,
  Pill,
  Crown,
  Home,
  Plane,
  Scissors,
  Brain,
  Handshake,
  ShoppingBag,
  ShoppingCart,
  Sofa,
  Ban,
  Signpost,
  Rocket,
  HeartHandshake,
  Phone,
  MapPin,
  Percent,
  Gem,
  ChefHat,
  Shirt,
  Medal,
  Drama,
  Gift,
  Croissant,
  Sun,
  CloudSun,
  Globe,
  Sunrise,
  HeartPulse,
  Goal,
  Sprout,
  Puzzle,
  Blocks,
  Info,
  Coffee,
  Hotel,
  CalendarDays,
  CalendarX,
  CalendarClock,
  UserX,
  BanknoteX,
  Building,
  CircleDollarSign,
  type LucideIcon,
} from 'lucide-react'
import { cn } from '@/lib/utils'

/**
 * GaIcon — icon by stable name (names mirror the manifest's Material Symbols set,
 * resolved to lucide-react glyphs so there is no icon-font / CSP dependency).
 * Color inherits via currentColor; decorative by default.
 *
 * ĐÂY LÀ NGUỒN DUY NHẤT của icon trong UI /v2. Không dùng emoji làm icon giao diện:
 * emoji do font hệ điều hành vẽ nên mỗi máy một kiểu, luôn nhiều màu, không nhận
 * `currentColor` và không có nét đồng bộ với sidebar — đặt cạnh icon Lucide là lộ ngay.
 * Emoji CHỈ còn được giữ ở ba chỗ nó là NỘI DUNG chứ không phải icon: avatar mentor/persona,
 * cờ quốc gia (🇩🇪 🇻🇳 🇬🇧 — Lucide không có cờ), và tranh SVG của nhân vật Speaking.
 */
const ICONS: Record<string, LucideIcon> = {
  dashboard: LayoutDashboard,
  calendar_month: Calendar,
  groups: Users,
  group: Users,
  grading: ClipboardCheck,
  monitoring: LineChart,
  notifications: Bell,
  spellcheck: SpellCheck,
  description: FileText,
  image: ImageIcon,
  person: User,
  chat: MessageSquare,
  group_add: UserPlus,
  error: AlertCircle,
  table_rows: Table,
  inbox: Inbox,
  payments: CreditCard,
  toll: Coins,
  corporate_fare: Building2,
  sell: Tag,
  menu_book: BookOpen,
  photo_library: Images,
  tune: SlidersHorizontal,
  campaign: Megaphone,
  record_voice_over: Mic,
  forum: MessagesSquare,
  receipt_long: ReceiptText,
  school: GraduationCap,
  badge: BadgeCheck,
  account_balance: Landmark,
  receipt: Receipt,
  mail: Mail,
  admin_panel_settings: ShieldCheck,
  settings: Settings,
  checklist: ListChecks,
  co_present: Presentation,
  search: Search,
  help: HelpCircle,
  logout: LogOut,
  draw: PenLine,
  quiz: FileQuestion,
  trending_up: TrendingUp,
  mic: Mic,
  assessment: ClipboardList,
  database: Database,
  repeat: Repeat,
  play_circle: PlayCircle,
  route: Route,
  emoji_events: Trophy,
  schedule: Clock,
  assignment: ClipboardList,
  library_books: Library,
  sports_esports: Gamepad2,
  newspaper: Newspaper,
  workspace_premium: Award,
  fact_check: BadgeCheck,
  // Dùng bởi nav item `st-exercise-history` + EmptyState của /v2/student/exercise-history.
  // Thiếu khoá này thì GaIcon rơi về fallback `Circle` (một vòng tròn trống) — trông như lỗi UI.
  history: History,
  // Điều hướng mobile: mở/đóng ngăn kéo sidebar (GaTopBar hamburger + GaSidebar nút đóng).
  menu: Menu,
  close: X,
  // Ba khoá dưới đây nav.ts ĐÃ tham chiếu từ trước nhưng bảng này chưa có, nên "Chấm công"
  // (teacher + org), "Giáo viên tự do" và "Thống kê" (học viên) vẽ ra một vòng tròn rỗng.
  timer: Timer,
  query_stats: ChartNoAxesCombined,
  person_search: UserSearch,

  // ── Trạng thái & hành động ────────────────────────────────────────────────
  // Thay cho ✅ ❌ ⚠️ 💡 🎉 ✨ 👍 🔒 💾 ✏️ 🔄 🔊 🎧 🤖 👁️ ⚡ 🔥 ⭐ trong nội dung bài học.
  check: Check,
  check_circle: CircleCheck,
  cancel: CircleX,
  warning: TriangleAlert,
  lightbulb: Lightbulb,
  celebration: PartyPopper,
  auto_awesome: Sparkles,
  thumb_up: ThumbsUp,
  lock: Lock,
  lock_open: Unlock,
  save: Save,
  edit: Pencil,
  refresh: RefreshCw,
  volume_up: Volume2,
  headphones: Headphones,
  smart_toy: Bot,
  format_quote: Quote,
  visibility: Eye,
  target: Target,
  bolt: Zap,
  local_fire_department: Flame,
  star: Star,
  flag: Flag,

  // ── Chủ đề node lộ trình ──────────────────────────────────────────────────
  // Đích đến của `emojiIconMap.ts` (emoji trong `skill_tree_nodes.emoji` → tên ở đây).
  alphabet: Type,
  numbers: Hash,
  straighten: Ruler,
  waving_hand: Hand,
  palette: Palette,
  restaurant: Utensils,
  stethoscope: Stethoscope,
  directions_bus: Bus,
  computer: Monitor,
  build: Wrench,
  link: LinkIcon,
  work: Briefcase,
  fitness: Dumbbell,
  medication: Pill,
  crown: Crown,
  home: Home,
  flight: Plane,
  content_cut: Scissors,
  psychology: Brain,
  handshake: Handshake,
  shopping_bag: ShoppingBag,
  shopping_cart: ShoppingCart,
  chair: Sofa,
  block: Ban,
  signpost: Signpost,
  rocket: Rocket,
  volunteer_activism: HeartHandshake,
  call: Phone,
  place: MapPin,
  percent: Percent,
  diamond: Gem,
  chef: ChefHat,
  apparel: Shirt,
  military_tech: Medal,
  theater_comedy: Drama,
  gift: Gift,
  bakery: Croissant,
  sunny: Sun,
  partly_cloudy: CloudSun,
  public: Globe,
  sunrise: Sunrise,
  healing: HeartPulse,
  sports_soccer: Goal,
  eco: Sprout,
  extension: Puzzle,
  blocks: Blocks,
  info: Info,
  coffee: Coffee,
  hotel: Hotel,

  // ── TYPE_ICON của notifications (notificationDisplay.ts) ─────────────────
  // Thiếu khoá nào thì bell dropdown + toast thông báo rơi về Circle rỗng trông như lỗi UI.
  event: CalendarDays,
  // Chevron nhóm local nav (B-05) + nhóm Khám phá của Lernen — thiếu là rơi về Circle rỗng.
  expand_more: ChevronDown,
  explore: Compass,
  event_busy: CalendarX,
  edit_calendar: CalendarClock,
  person_off: UserX,
  money_off: BanknoteX,
  apartment: Building,
  paid: CircleDollarSign,
}

/** Tên icon hợp lệ có trong bảng — dùng để test bao phủ, không dùng để render. */
export const GA_ICON_NAMES = Object.keys(ICONS)

export interface GaIconProps {
  name: string
  size?: number
  title?: string
  className?: string
}

export function GaIcon({ name, size = 18, title, className }: GaIconProps) {
  const Cmp = ICONS[name] ?? Circle
  return (
    <Cmp
      size={size}
      strokeWidth={1.9}
      className={cn('shrink-0', className)}
      aria-hidden={title ? undefined : true}
      role={title ? 'img' : undefined}
      aria-label={title}
    />
  )
}
