// Galerie 2.0 (UI 2.0) component library — foundational set (Phase 1).
// Per-screen components (charts, schedule grid, learning tree, …) land in Phase 2.
export { GaShell } from './GaShell'
export { GaSidebar } from './GaSidebar'
export { GaPageHdr } from './GaPageHdr'
export { GaLogo } from './GaLogo'
export { GaBtn } from './GaBtn'
export { GaCap } from './GaCap'
export { GaIcon } from './GaIcon'
export { GaMedia } from './GaMedia'
export { GaCard, GaCardHeader, GaCardTitle, GaCardBody } from './GaCard'
export { TkBadge } from './TkBadge'
export { TkTabs, TkTabsList, TkTabsTrigger, TkTabsContent } from './TkTabs'
export { TkSearch } from './TkSearch'
export { TkSeg } from './TkSeg'
export type { TkSegOption } from './TkSeg'
export { TkModal } from './TkModal'
export { DataTable } from './DataTable'
export type { DataTableColumn, DataTableProps } from './DataTable'
export { AdStatStrip } from './AdStat'
export type { AdStatCell } from './AdStat'
export { TkStatStrip } from './TkStatStrip'
export type { TkStatItem } from './TkStatStrip'
export { EmptyState } from './EmptyState'
export { ErrorBanner } from './ErrorBanner'
export { SkeletonRow } from './SkeletonRow'
export { LoadingState } from './LoadingState'
export { ROLE_NAV, teacherNav, adminNav, orgNav } from './nav'
export type { RoleId, RoleNav, NavSection, NavItem } from './nav'
