-- ============================================================
-- V10: SEED A1 VOCABULARY Part 2 (Neuter nouns + Common verbs)
-- ============================================================

-- Common Nouns (Neuter - DAS)
INSERT INTO words (dtype, base_form, cefr_level, created_at, updated_at) VALUES
('Noun', 'Kind', 'A1', NOW(), NOW()),
('Noun', 'Haus', 'A1', NOW(), NOW()),
('Noun', 'Buch', 'A1', NOW(), NOW()),
('Noun', 'Auto', 'A1', NOW(), NOW()),
('Noun', 'Zimmer', 'A1', NOW(), NOW()),
('Noun', 'Fenster', 'A1', NOW(), NOW()),
('Noun', 'Bett', 'A1', NOW(), NOW()),
('Noun', 'Brot', 'A1', NOW(), NOW()),
('Noun', 'Wasser', 'A1', NOW(), NOW()),
('Noun', 'Bier', 'A1', NOW(), NOW()),
('Noun', 'Glas', 'A1', NOW(), NOW()),
('Noun', 'Ei', 'A1', NOW(), NOW()),
('Noun', 'Fleisch', 'A1', NOW(), NOW()),
('Noun', 'Gemüse', 'A1', NOW(), NOW()),
('Noun', 'Obst', 'A1', NOW(), NOW()),
('Noun', 'Jahr', 'A1', NOW(), NOW()),
('Noun', 'Land', 'A1', NOW(), NOW()),
('Noun', 'Wetter', 'A1', NOW(), NOW()),
('Noun', 'Geld', 'A1', NOW(), NOW()),
('Noun', 'Handy', 'A1', NOW(), NOW());

INSERT INTO nouns (id, gender, plural_form, genitive_form, noun_type) VALUES
((SELECT id FROM words WHERE base_form = 'Kind' AND dtype = 'Noun'), 'DAS', 'Kinder', 'Kindes', 'STARK'),
((SELECT id FROM words WHERE base_form = 'Haus' AND dtype = 'Noun'), 'DAS', 'Häuser', 'Hauses', 'STARK'),
((SELECT id FROM words WHERE base_form = 'Buch' AND dtype = 'Noun'), 'DAS', 'Bücher', 'Buches', 'STARK'),
((SELECT id FROM words WHERE base_form = 'Auto' AND dtype = 'Noun'), 'DAS', 'Autos', 'Autos', 'STARK'),
((SELECT id FROM words WHERE base_form = 'Zimmer' AND dtype = 'Noun'), 'DAS', 'Zimmer', 'Zimmers', 'STARK'),
((SELECT id FROM words WHERE base_form = 'Fenster' AND dtype = 'Noun'), 'DAS', 'Fenster', 'Fensters', 'STARK'),
((SELECT id FROM words WHERE base_form = 'Bett' AND dtype = 'Noun'), 'DAS', 'Betten', 'Bettes', 'STARK'),
((SELECT id FROM words WHERE base_form = 'Brot' AND dtype = 'Noun'), 'DAS', 'Brote', 'Brotes', 'STARK'),
((SELECT id FROM words WHERE base_form = 'Wasser' AND dtype = 'Noun'), 'DAS', 'Wasser', 'Wassers', 'STARK'),
((SELECT id FROM words WHERE base_form = 'Bier' AND dtype = 'Noun'), 'DAS', 'Biere', 'Bieres', 'STARK'),
((SELECT id FROM words WHERE base_form = 'Glas' AND dtype = 'Noun'), 'DAS', 'Gläser', 'Glases', 'STARK'),
((SELECT id FROM words WHERE base_form = 'Ei' AND dtype = 'Noun'), 'DAS', 'Eier', 'Eies', 'STARK'),
((SELECT id FROM words WHERE base_form = 'Fleisch' AND dtype = 'Noun'), 'DAS', 'Fleisch', 'Fleisches', 'STARK'),
((SELECT id FROM words WHERE base_form = 'Gemüse' AND dtype = 'Noun'), 'DAS', 'Gemüse', 'Gemüses', 'STARK'),
((SELECT id FROM words WHERE base_form = 'Obst' AND dtype = 'Noun'), 'DAS', 'Obst', 'Obstes', 'STARK'),
((SELECT id FROM words WHERE base_form = 'Jahr' AND dtype = 'Noun'), 'DAS', 'Jahre', 'Jahres', 'STARK'),
((SELECT id FROM words WHERE base_form = 'Land' AND dtype = 'Noun'), 'DAS', 'Länder', 'Landes', 'STARK'),
((SELECT id FROM words WHERE base_form = 'Wetter' AND dtype = 'Noun'), 'DAS', 'Wetter', 'Wetters', 'STARK'),
((SELECT id FROM words WHERE base_form = 'Geld' AND dtype = 'Noun'), 'DAS', 'Gelder', 'Geldes', 'STARK'),
((SELECT id FROM words WHERE base_form = 'Handy' AND dtype = 'Noun'), 'DAS', 'Handys', 'Handys', 'STARK');

INSERT INTO word_translations (word_id, locale, meaning, example) VALUES
((SELECT id FROM words WHERE base_form = 'Kind' AND dtype = 'Noun'), 'vi', 'đứa trẻ', 'Das Kind spielt. (Đứa trẻ đang chơi.)'),
((SELECT id FROM words WHERE base_form = 'Kind' AND dtype = 'Noun'), 'en', 'child', 'The child is playing.'),
((SELECT id FROM words WHERE base_form = 'Haus' AND dtype = 'Noun'), 'vi', 'ngôi nhà', 'Das Haus ist schön. (Ngôi nhà đẹp.)'),
((SELECT id FROM words WHERE base_form = 'Haus' AND dtype = 'Noun'), 'en', 'house', 'The house is beautiful.'),
((SELECT id FROM words WHERE base_form = 'Buch' AND dtype = 'Noun'), 'vi', 'quyển sách', 'Das Buch ist interessant. (Quyển sách thú vị.)'),
((SELECT id FROM words WHERE base_form = 'Buch' AND dtype = 'Noun'), 'en', 'book', 'The book is interesting.'),
((SELECT id FROM words WHERE base_form = 'Auto' AND dtype = 'Noun'), 'vi', 'xe hơi', 'Das Auto ist schnell. (Xe hơi nhanh.)'),
((SELECT id FROM words WHERE base_form = 'Auto' AND dtype = 'Noun'), 'en', 'car', 'The car is fast.'),
((SELECT id FROM words WHERE base_form = 'Zimmer' AND dtype = 'Noun'), 'vi', 'căn phòng', 'Das Zimmer ist groß. (Căn phòng rộng.)'),
((SELECT id FROM words WHERE base_form = 'Zimmer' AND dtype = 'Noun'), 'en', 'room', 'The room is big.'),
((SELECT id FROM words WHERE base_form = 'Fenster' AND dtype = 'Noun'), 'vi', 'cửa sổ', 'Das Fenster ist offen. (Cửa sổ đang mở.)'),
((SELECT id FROM words WHERE base_form = 'Fenster' AND dtype = 'Noun'), 'en', 'window', 'The window is open.'),
((SELECT id FROM words WHERE base_form = 'Bett' AND dtype = 'Noun'), 'vi', 'giường', 'Das Bett ist bequem. (Giường thoải mái.)'),
((SELECT id FROM words WHERE base_form = 'Bett' AND dtype = 'Noun'), 'en', 'bed', 'The bed is comfortable.'),
((SELECT id FROM words WHERE base_form = 'Brot' AND dtype = 'Noun'), 'vi', 'bánh mì', 'Das Brot ist frisch. (Bánh mì tươi.)'),
((SELECT id FROM words WHERE base_form = 'Brot' AND dtype = 'Noun'), 'en', 'bread', 'The bread is fresh.'),
((SELECT id FROM words WHERE base_form = 'Wasser' AND dtype = 'Noun'), 'vi', 'nước', 'Ich trinke Wasser. (Tôi uống nước.)'),
((SELECT id FROM words WHERE base_form = 'Wasser' AND dtype = 'Noun'), 'en', 'water', 'I drink water.'),
((SELECT id FROM words WHERE base_form = 'Bier' AND dtype = 'Noun'), 'vi', 'bia', 'Das Bier ist kalt. (Bia lạnh.)'),
((SELECT id FROM words WHERE base_form = 'Bier' AND dtype = 'Noun'), 'en', 'beer', 'The beer is cold.'),
((SELECT id FROM words WHERE base_form = 'Glas' AND dtype = 'Noun'), 'vi', 'cái ly', 'Das Glas ist voll. (Cái ly đầy.)'),
((SELECT id FROM words WHERE base_form = 'Glas' AND dtype = 'Noun'), 'en', 'glass', 'The glass is full.'),
((SELECT id FROM words WHERE base_form = 'Ei' AND dtype = 'Noun'), 'vi', 'quả trứng', 'Ich esse ein Ei. (Tôi ăn một quả trứng.)'),
((SELECT id FROM words WHERE base_form = 'Ei' AND dtype = 'Noun'), 'en', 'egg', 'I eat an egg.'),
((SELECT id FROM words WHERE base_form = 'Fleisch' AND dtype = 'Noun'), 'vi', 'thịt', 'Das Fleisch ist lecker. (Thịt ngon.)'),
((SELECT id FROM words WHERE base_form = 'Fleisch' AND dtype = 'Noun'), 'en', 'meat', 'The meat is delicious.'),
((SELECT id FROM words WHERE base_form = 'Gemüse' AND dtype = 'Noun'), 'vi', 'rau củ', 'Ich esse Gemüse. (Tôi ăn rau.)'),
((SELECT id FROM words WHERE base_form = 'Gemüse' AND dtype = 'Noun'), 'en', 'vegetables', 'I eat vegetables.'),
((SELECT id FROM words WHERE base_form = 'Obst' AND dtype = 'Noun'), 'vi', 'trái cây', 'Obst ist gesund. (Trái cây tốt cho sức khỏe.)'),
((SELECT id FROM words WHERE base_form = 'Obst' AND dtype = 'Noun'), 'en', 'fruit', 'Fruit is healthy.'),
((SELECT id FROM words WHERE base_form = 'Jahr' AND dtype = 'Noun'), 'vi', 'năm', 'Ein Jahr hat 12 Monate. (Một năm có 12 tháng.)'),
((SELECT id FROM words WHERE base_form = 'Jahr' AND dtype = 'Noun'), 'en', 'year', 'A year has 12 months.'),
((SELECT id FROM words WHERE base_form = 'Land' AND dtype = 'Noun'), 'vi', 'đất nước', 'Deutschland ist ein Land. (Đức là một đất nước.)'),
((SELECT id FROM words WHERE base_form = 'Land' AND dtype = 'Noun'), 'en', 'country', 'Germany is a country.'),
((SELECT id FROM words WHERE base_form = 'Wetter' AND dtype = 'Noun'), 'vi', 'thời tiết', 'Das Wetter ist schön. (Thời tiết đẹp.)'),
((SELECT id FROM words WHERE base_form = 'Wetter' AND dtype = 'Noun'), 'en', 'weather', 'The weather is nice.'),
((SELECT id FROM words WHERE base_form = 'Geld' AND dtype = 'Noun'), 'vi', 'tiền', 'Ich brauche Geld. (Tôi cần tiền.)'),
((SELECT id FROM words WHERE base_form = 'Geld' AND dtype = 'Noun'), 'en', 'money', 'I need money.'),
((SELECT id FROM words WHERE base_form = 'Handy' AND dtype = 'Noun'), 'vi', 'điện thoại di động', 'Mein Handy ist neu. (Điện thoại của tôi mới.)'),
((SELECT id FROM words WHERE base_form = 'Handy' AND dtype = 'Noun'), 'en', 'mobile phone', 'My phone is new.');

-- Common Verbs (A1 Level)
INSERT INTO words (dtype, base_form, cefr_level, created_at, updated_at) VALUES
('Verb', 'sein', 'A1', NOW(), NOW()),
('Verb', 'haben', 'A1', NOW(), NOW()),
('Verb', 'werden', 'A1', NOW(), NOW()),
('Verb', 'können', 'A1', NOW(), NOW()),
('Verb', 'müssen', 'A1', NOW(), NOW()),
('Verb', 'sagen', 'A1', NOW(), NOW()),
('Verb', 'machen', 'A1', NOW(), NOW()),
('Verb', 'geben', 'A1', NOW(), NOW()),
('Verb', 'kommen', 'A1', NOW(), NOW()),
('Verb', 'gehen', 'A1', NOW(), NOW()),
('Verb', 'wissen', 'A1', NOW(), NOW()),
('Verb', 'sehen', 'A1', NOW(), NOW()),
('Verb', 'wollen', 'A1', NOW(), NOW()),
('Verb', 'finden', 'A1', NOW(), NOW()),
('Verb', 'heißen', 'A1', NOW(), NOW()),
('Verb', 'essen', 'A1', NOW(), NOW()),
('Verb', 'trinken', 'A1', NOW(), NOW()),
('Verb', 'sprechen', 'A1', NOW(), NOW()),
('Verb', 'lernen', 'A1', NOW(), NOW()),
('Verb', 'arbeiten', 'A1', NOW(), NOW());

INSERT INTO verbs (id, auxiliary_verb, partizip2, is_separable, is_irregular) VALUES
((SELECT id FROM words WHERE base_form = 'sein' AND dtype = 'Verb'), 'SEIN', 'gewesen', FALSE, TRUE),
((SELECT id FROM words WHERE base_form = 'haben' AND dtype = 'Verb'), 'HABEN', 'gehabt', FALSE, TRUE),
((SELECT id FROM words WHERE base_form = 'werden' AND dtype = 'Verb'), 'SEIN', 'geworden', FALSE, TRUE),
((SELECT id FROM words WHERE base_form = 'können' AND dtype = 'Verb'), 'HABEN', 'gekonnt', FALSE, TRUE),
((SELECT id FROM words WHERE base_form = 'müssen' AND dtype = 'Verb'), 'HABEN', 'gemusst', FALSE, TRUE),
((SELECT id FROM words WHERE base_form = 'sagen' AND dtype = 'Verb'), 'HABEN', 'gesagt', FALSE, FALSE),
((SELECT id FROM words WHERE base_form = 'machen' AND dtype = 'Verb'), 'HABEN', 'gemacht', FALSE, FALSE),
((SELECT id FROM words WHERE base_form = 'geben' AND dtype = 'Verb'), 'HABEN', 'gegeben', FALSE, TRUE),
((SELECT id FROM words WHERE base_form = 'kommen' AND dtype = 'Verb'), 'SEIN', 'gekommen', FALSE, TRUE),
((SELECT id FROM words WHERE base_form = 'gehen' AND dtype = 'Verb'), 'SEIN', 'gegangen', FALSE, TRUE),
((SELECT id FROM words WHERE base_form = 'wissen' AND dtype = 'Verb'), 'HABEN', 'gewusst', FALSE, TRUE),
((SELECT id FROM words WHERE base_form = 'sehen' AND dtype = 'Verb'), 'HABEN', 'gesehen', FALSE, TRUE),
((SELECT id FROM words WHERE base_form = 'wollen' AND dtype = 'Verb'), 'HABEN', 'gewollt', FALSE, TRUE),
((SELECT id FROM words WHERE base_form = 'finden' AND dtype = 'Verb'), 'HABEN', 'gefunden', FALSE, TRUE),
((SELECT id FROM words WHERE base_form = 'heißen' AND dtype = 'Verb'), 'HABEN', 'geheißen', FALSE, TRUE),
((SELECT id FROM words WHERE base_form = 'essen' AND dtype = 'Verb'), 'HABEN', 'gegessen', FALSE, TRUE),
((SELECT id FROM words WHERE base_form = 'trinken' AND dtype = 'Verb'), 'HABEN', 'getrunken', FALSE, TRUE),
((SELECT id FROM words WHERE base_form = 'sprechen' AND dtype = 'Verb'), 'HABEN', 'gesprochen', FALSE, TRUE),
((SELECT id FROM words WHERE base_form = 'lernen' AND dtype = 'Verb'), 'HABEN', 'gelernt', FALSE, FALSE),
((SELECT id FROM words WHERE base_form = 'arbeiten' AND dtype = 'Verb'), 'HABEN', 'gearbeitet', FALSE, FALSE);

-- Verb conjugations (Present tense - Präsens)
INSERT INTO verb_conjugations (verb_id, tense, pronoun, form) VALUES
-- sein
((SELECT id FROM words WHERE base_form = 'sein' AND dtype = 'Verb'), 'PRASENS', 'ICH', 'bin'),
((SELECT id FROM words WHERE base_form = 'sein' AND dtype = 'Verb'), 'PRASENS', 'DU', 'bist'),
((SELECT id FROM words WHERE base_form = 'sein' AND dtype = 'Verb'), 'PRASENS', 'ER_SIE_ES', 'ist'),
((SELECT id FROM words WHERE base_form = 'sein' AND dtype = 'Verb'), 'PRASENS', 'WIR', 'sind'),
((SELECT id FROM words WHERE base_form = 'sein' AND dtype = 'Verb'), 'PRASENS', 'IHR', 'seid'),
((SELECT id FROM words WHERE base_form = 'sein' AND dtype = 'Verb'), 'PRASENS', 'SIE_FORMAL', 'sind'),
-- haben
((SELECT id FROM words WHERE base_form = 'haben' AND dtype = 'Verb'), 'PRASENS', 'ICH', 'habe'),
((SELECT id FROM words WHERE base_form = 'haben' AND dtype = 'Verb'), 'PRASENS', 'DU', 'hast'),
((SELECT id FROM words WHERE base_form = 'haben' AND dtype = 'Verb'), 'PRASENS', 'ER_SIE_ES', 'hat'),
((SELECT id FROM words WHERE base_form = 'haben' AND dtype = 'Verb'), 'PRASENS', 'WIR', 'haben'),
((SELECT id FROM words WHERE base_form = 'haben' AND dtype = 'Verb'), 'PRASENS', 'IHR', 'habt'),
((SELECT id FROM words WHERE base_form = 'haben' AND dtype = 'Verb'), 'PRASENS', 'SIE_FORMAL', 'haben'),
-- werden
((SELECT id FROM words WHERE base_form = 'werden' AND dtype = 'Verb'), 'PRASENS', 'ICH', 'werde'),
((SELECT id FROM words WHERE base_form = 'werden' AND dtype = 'Verb'), 'PRASENS', 'DU', 'wirst'),
((SELECT id FROM words WHERE base_form = 'werden' AND dtype = 'Verb'), 'PRASENS', 'ER_SIE_ES', 'wird'),
((SELECT id FROM words WHERE base_form = 'werden' AND dtype = 'Verb'), 'PRASENS', 'WIR', 'werden'),
((SELECT id FROM words WHERE base_form = 'werden' AND dtype = 'Verb'), 'PRASENS', 'IHR', 'werdet'),
((SELECT id FROM words WHERE base_form = 'werden' AND dtype = 'Verb'), 'PRASENS', 'SIE_FORMAL', 'werden'),
-- können
((SELECT id FROM words WHERE base_form = 'können' AND dtype = 'Verb'), 'PRASENS', 'ICH', 'kann'),
((SELECT id FROM words WHERE base_form = 'können' AND dtype = 'Verb'), 'PRASENS', 'DU', 'kannst'),
((SELECT id FROM words WHERE base_form = 'können' AND dtype = 'Verb'), 'PRASENS', 'ER_SIE_ES', 'kann'),
((SELECT id FROM words WHERE base_form = 'können' AND dtype = 'Verb'), 'PRASENS', 'WIR', 'können'),
((SELECT id FROM words WHERE base_form = 'können' AND dtype = 'Verb'), 'PRASENS', 'IHR', 'könnt'),
((SELECT id FROM words WHERE base_form = 'können' AND dtype = 'Verb'), 'PRASENS', 'SIE_FORMAL', 'können'),
-- müssen
((SELECT id FROM words WHERE base_form = 'müssen' AND dtype = 'Verb'), 'PRASENS', 'ICH', 'muss'),
((SELECT id FROM words WHERE base_form = 'müssen' AND dtype = 'Verb'), 'PRASENS', 'DU', 'musst'),
((SELECT id FROM words WHERE base_form = 'müssen' AND dtype = 'Verb'), 'PRASENS', 'ER_SIE_ES', 'muss'),
((SELECT id FROM words WHERE base_form = 'müssen' AND dtype = 'Verb'), 'PRASENS', 'WIR', 'müssen'),
((SELECT id FROM words WHERE base_form = 'müssen' AND dtype = 'Verb'), 'PRASENS', 'IHR', 'müsst'),
((SELECT id FROM words WHERE base_form = 'müssen' AND dtype = 'Verb'), 'PRASENS', 'SIE_FORMAL', 'müssen');

-- Verb translations
INSERT INTO word_translations (word_id, locale, meaning, example) VALUES
((SELECT id FROM words WHERE base_form = 'sein' AND dtype = 'Verb'), 'vi', 'là, thì, ở', 'Ich bin Student. (Tôi là sinh viên.)'),
((SELECT id FROM words WHERE base_form = 'sein' AND dtype = 'Verb'), 'en', 'to be', 'I am a student.'),
((SELECT id FROM words WHERE base_form = 'haben' AND dtype = 'Verb'), 'vi', 'có', 'Ich habe einen Hund. (Tôi có một con chó.)'),
((SELECT id FROM words WHERE base_form = 'haben' AND dtype = 'Verb'), 'en', 'to have', 'I have a dog.'),
((SELECT id FROM words WHERE base_form = 'werden' AND dtype = 'Verb'), 'vi', 'trở thành', 'Ich werde Arzt. (Tôi sẽ trở thành bác sĩ.)'),
((SELECT id FROM words WHERE base_form = 'werden' AND dtype = 'Verb'), 'en', 'to become', 'I will become a doctor.'),
((SELECT id FROM words WHERE base_form = 'können' AND dtype = 'Verb'), 'vi', 'có thể', 'Ich kann Deutsch sprechen. (Tôi có thể nói tiếng Đức.)'),
((SELECT id FROM words WHERE base_form = 'können' AND dtype = 'Verb'), 'en', 'can, to be able to', 'I can speak German.'),
((SELECT id FROM words WHERE base_form = 'müssen' AND dtype = 'Verb'), 'vi', 'phải', 'Ich muss lernen. (Tôi phải học.)'),
((SELECT id FROM words WHERE base_form = 'müssen' AND dtype = 'Verb'), 'en', 'must, to have to', 'I must study.'),
((SELECT id FROM words WHERE base_form = 'sagen' AND dtype = 'Verb'), 'vi', 'nói', 'Er sagt die Wahrheit. (Anh ấy nói sự thật.)'),
((SELECT id FROM words WHERE base_form = 'sagen' AND dtype = 'Verb'), 'en', 'to say', 'He says the truth.'),
((SELECT id FROM words WHERE base_form = 'machen' AND dtype = 'Verb'), 'vi', 'làm', 'Ich mache Hausaufgaben. (Tôi làm bài tập về nhà.)'),
((SELECT id FROM words WHERE base_form = 'machen' AND dtype = 'Verb'), 'en', 'to do, to make', 'I do homework.'),
((SELECT id FROM words WHERE base_form = 'geben' AND dtype = 'Verb'), 'vi', 'cho', 'Ich gebe dir das Buch. (Tôi cho bạn quyển sách.)'),
((SELECT id FROM words WHERE base_form = 'geben' AND dtype = 'Verb'), 'en', 'to give', 'I give you the book.'),
((SELECT id FROM words WHERE base_form = 'kommen' AND dtype = 'Verb'), 'vi', 'đến', 'Ich komme aus Vietnam. (Tôi đến từ Việt Nam.)'),
((SELECT id FROM words WHERE base_form = 'kommen' AND dtype = 'Verb'), 'en', 'to come', 'I come from Vietnam.'),
((SELECT id FROM words WHERE base_form = 'gehen' AND dtype = 'Verb'), 'vi', 'đi', 'Ich gehe zur Schule. (Tôi đi học.)'),
((SELECT id FROM words WHERE base_form = 'gehen' AND dtype = 'Verb'), 'en', 'to go', 'I go to school.'),
((SELECT id FROM words WHERE base_form = 'wissen' AND dtype = 'Verb'), 'vi', 'biết', 'Ich weiß es nicht. (Tôi không biết.)'),
((SELECT id FROM words WHERE base_form = 'wissen' AND dtype = 'Verb'), 'en', 'to know', 'I don''t know.'),
((SELECT id FROM words WHERE base_form = 'sehen' AND dtype = 'Verb'), 'vi', 'nhìn thấy', 'Ich sehe dich. (Tôi nhìn thấy bạn.)'),
((SELECT id FROM words WHERE base_form = 'sehen' AND dtype = 'Verb'), 'en', 'to see', 'I see you.'),
((SELECT id FROM words WHERE base_form = 'wollen' AND dtype = 'Verb'), 'vi', 'muốn', 'Ich will Deutsch lernen. (Tôi muốn học tiếng Đức.)'),
((SELECT id FROM words WHERE base_form = 'wollen' AND dtype = 'Verb'), 'en', 'to want', 'I want to learn German.'),
((SELECT id FROM words WHERE base_form = 'finden' AND dtype = 'Verb'), 'vi', 'tìm thấy', 'Ich finde das Buch. (Tôi tìm thấy quyển sách.)'),
((SELECT id FROM words WHERE base_form = 'finden' AND dtype = 'Verb'), 'en', 'to find', 'I find the book.'),
((SELECT id FROM words WHERE base_form = 'heißen' AND dtype = 'Verb'), 'vi', 'tên là', 'Ich heiße Anna. (Tôi tên là Anna.)'),
((SELECT id FROM words WHERE base_form = 'heißen' AND dtype = 'Verb'), 'en', 'to be called', 'My name is Anna.'),
((SELECT id FROM words WHERE base_form = 'essen' AND dtype = 'Verb'), 'vi', 'ăn', 'Ich esse Brot. (Tôi ăn bánh mì.)'),
((SELECT id FROM words WHERE base_form = 'essen' AND dtype = 'Verb'), 'en', 'to eat', 'I eat bread.'),
((SELECT id FROM words WHERE base_form = 'trinken' AND dtype = 'Verb'), 'vi', 'uống', 'Ich trinke Wasser. (Tôi uống nước.)'),
((SELECT id FROM words WHERE base_form = 'trinken' AND dtype = 'Verb'), 'en', 'to drink', 'I drink water.'),
((SELECT id FROM words WHERE base_form = 'sprechen' AND dtype = 'Verb'), 'vi', 'nói', 'Ich spreche Deutsch. (Tôi nói tiếng Đức.)'),
((SELECT id FROM words WHERE base_form = 'sprechen' AND dtype = 'Verb'), 'en', 'to speak', 'I speak German.'),
((SELECT id FROM words WHERE base_form = 'lernen' AND dtype = 'Verb'), 'vi', 'học', 'Ich lerne Deutsch. (Tôi học tiếng Đức.)'),
((SELECT id FROM words WHERE base_form = 'lernen' AND dtype = 'Verb'), 'en', 'to learn', 'I learn German.'),
((SELECT id FROM words WHERE base_form = 'arbeiten' AND dtype = 'Verb'), 'vi', 'làm việc', 'Ich arbeite in Berlin. (Tôi làm việc ở Berlin.)'),
((SELECT id FROM words WHERE base_form = 'arbeiten' AND dtype = 'Verb'), 'en', 'to work', 'I work in Berlin.');
