-- ============================================================
-- V113: Seed Sample Goethe-Zertifikat B1 Exam Data
-- Generated by python scraper
-- ============================================================

INSERT INTO practice_exercises (
    exercise_type, 
    cefr_level, 
    skill_type, 
    exam_name, 
    content_json, 
    source_name, 
    source_url, 
    xp_reward
) VALUES (
    'EXAM',
    'B1',
    'READING',
    'Goethe-Zertifikat B1 Modellsatz - Lesen',
    '{"title": "Lesen Teil 1: E-Mail lesen", "instructions": "Lesen Sie den Text und kreuzen Sie an: Richtig oder Falsch?", "readingText": "Liebe Nachbarn, \nwie Sie wissen, feiere ich am Samstag meinen Geburtstag. Die Party findet im Garten statt. Ich hoffe, dass das Wetter schön bleibt. Es wird Musik geben, aber ab 22 Uhr werden wir leiser sein. Bitte entschuldigen Sie den Lärm. Sie sind natürlich auch herzlich eingeladen! \nViele Grüße, Thomas", "questions": [{"id": "q1", "type": "TRUE_FALSE", "question": "Thomas feiert seinen Geburtstag im Haus.", "options": ["Richtig", "Falsch"], "correctAnswer": "Falsch", "explanation": "Die Party findet im Garten statt."}, {"id": "q2", "type": "TRUE_FALSE", "question": "Thomas lädt auch seine Nachbarn zur Party ein.", "options": ["Richtig", "Falsch"], "correctAnswer": "Richtig", "explanation": "Sie sind natürlich auch herzlich eingeladen!"}, {"id": "q3", "type": "TRUE_FALSE", "question": "Nach 22 Uhr gibt es keine Musik mehr.", "options": ["Richtig", "Falsch"], "correctAnswer": "Falsch", "explanation": "Es wird Musik geben, aber ab 22 Uhr werden wir leiser sein. (Musik noch da, nur leiser)"}]}'::jsonb,
    'Goethe-Institut',
    'https://www.goethe.de/ins/vn/vi/sta/hcm/prf/bar.html',
    100
);
