-- Phase 1: Spaced Repetition Scheduler (SM-2 Algorithm)
-- Tracks learning schedule for vocabulary retention

CREATE TABLE IF NOT EXISTS spaced_repetition_schedule (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    word_id BIGINT NOT NULL,
    last_review_date TIMESTAMP,
    next_review_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    review_count INT DEFAULT 0,
    easiness_factor DOUBLE PRECISION DEFAULT 2.5,
    interval INT DEFAULT 1,
    retention_status VARCHAR(20) DEFAULT 'LEARNING',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (word_id) REFERENCES words(id) ON DELETE CASCADE,
    CONSTRAINT unique_user_word UNIQUE(user_id, word_id)
);

CREATE INDEX IF NOT EXISTS idx_srs_user_next_review ON spaced_repetition_schedule(user_id, next_review_date);
CREATE INDEX IF NOT EXISTS idx_srs_user_retention ON spaced_repetition_schedule(user_id, retention_status);
CREATE INDEX IF NOT EXISTS idx_srs_word_id ON spaced_repetition_schedule(word_id);

-- Dialogue templates for greeting practice
CREATE TABLE IF NOT EXISTS dialogue_templates (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    template_name VARCHAR(100) NOT NULL UNIQUE,
    difficulty_level INT DEFAULT 1,
    user_prompt_template TEXT NOT NULL,
    ai_system_prompt TEXT NOT NULL,
    expected_response_patterns TEXT,
    vocabulary_ids TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_dialogue_difficulty ON dialogue_templates(difficulty_level);
