-- Phase 1: Listening Practice Exercises
-- Tracks listening comprehension exercises for vocabulary learning

CREATE TABLE IF NOT EXISTS listening_practice_exercises (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    word_id BIGINT NOT NULL,
    exercise_type VARCHAR(30) NOT NULL,
    audio_url VARCHAR(255) NOT NULL,
    correct_answer VARCHAR(255) NOT NULL,
    options TEXT NOT NULL,
    difficulty_level INT DEFAULT 1,
    user_answer VARCHAR(255),
    is_correct BOOLEAN,
    confidence_score INT,
    completed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (word_id) REFERENCES words(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_listening_user_id ON listening_practice_exercises(user_id);
CREATE INDEX IF NOT EXISTS idx_listening_word_id ON listening_practice_exercises(word_id);
CREATE INDEX IF NOT EXISTS idx_listening_completed ON listening_practice_exercises(user_id, completed_at);

-- Error tracking for speaking sessions (basic)
CREATE TABLE IF NOT EXISTS ai_speaking_errors (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    session_id BIGINT NOT NULL,
    error_type VARCHAR(50) NOT NULL,
    user_input TEXT,
    ai_correction TEXT,
    severity VARCHAR(20) DEFAULT 'INFO',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (session_id) REFERENCES ai_speaking_sessions(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_errors_session ON ai_speaking_errors(session_id);
CREATE INDEX IF NOT EXISTS idx_errors_type ON ai_speaking_errors(error_type);
