-- Backfill the migration for the core in-app notification table.
-- The `user_notifications` entity shipped without a Flyway migration, which
-- breaks `ddl-auto: validate` on a fresh database. IF NOT EXISTS keeps this
-- idempotent for environments where the table was auto-created previously.

CREATE TABLE IF NOT EXISTS user_notifications (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_user_id BIGINT       NOT NULL,
    notification_type VARCHAR(64)  NOT NULL,
    payload_json      JSONB        NOT NULL DEFAULT '{}'::jsonb,
    read_at           TIMESTAMP    NULL,
    created_at        TIMESTAMP    NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_user_notifications_recipient
        FOREIGN KEY (recipient_user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_user_notifications_recipient_unread
    ON user_notifications (recipient_user_id, read_at, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_user_notifications_recipient_created
    ON user_notifications (recipient_user_id, created_at DESC);
