-- Scheduled admin broadcasts. A row is created when an admin submits a broadcast
-- with a future `scheduledAt`. A background job fans it out into per-recipient
-- user_notifications rows once it becomes due, then marks the row SENT/FAILED.

CREATE TABLE IF NOT EXISTS scheduled_broadcasts (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_type VARCHAR(64)  NOT NULL,
    audience_type     VARCHAR(32)  NOT NULL,
    tier              VARCHAR(32)  NULL,
    role              VARCHAR(32)  NULL,
    target_email      VARCHAR(255) NULL,
    title             VARCHAR(255) NOT NULL,
    body              TEXT         NOT NULL,
    scheduled_at      TIMESTAMP    NOT NULL,
    status            VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    recipient_count   INTEGER      NULL,
    error             TEXT         NULL,
    created_at        TIMESTAMP    NOT NULL DEFAULT NOW(),
    sent_at           TIMESTAMP    NULL
);

-- The dispatch job polls PENDING rows whose scheduled_at has passed.
CREATE INDEX IF NOT EXISTS idx_scheduled_broadcasts_due
    ON scheduled_broadcasts (status, scheduled_at);
