-- Đợt 3 — B1 (Goethe B1 modular + telc B1 ZD) cho mảng Luyện thi Nói.
-- prep_sec: Vorbereitungszeit hiệu lực của phiên (rút gọn 5′ mặc định / chuẩn thi thật theo blueprint).
-- Loại thẻ mới: PLANNING_CARD, FOLIEN_DECK (chọn 1/2 chủ đề), PARTNER_PRESENTATION (partner trình bày trước —
-- văn bản nằm ở khóa partner*, client không thấy, đi ra dưới dạng lượt nói), CONTACT_CARD, TOPIC_GRAPHIC_PAIR
-- (Vorlage A/B: phần partner* là đề riêng của AI partner). Số liệu biểu đồ là khảo sát HƯ CẤU (ghi rõ trong đề).
-- KHÔNG viết chuỗi đô-la + ngoặc nhọn ở bất kỳ đâu trong file (Flyway placeholder).

ALTER TABLE speaking_exam_sessions ADD COLUMN IF NOT EXISTS prep_sec INT;

-- Goethe B1 T2: thí sinh trình bày → partner nhận xét + hỏi → giám khảo hỏi (3 lượt thí sinh; partner có mặt).
UPDATE speaking_exam_blueprints
SET parts_json = jsonb_set(jsonb_set(parts_json, '{parts,1,maxCandidateTurns}', '3'::jsonb), '{parts,1,partnerRole}', '"PARTNER"'::jsonb)
WHERE provider = 'GOETHE' AND level = 'B1' AND version = 1;

-- ── Goethe B1 T1 / telc B1 T3 — Gemeinsam etwas planen / Gemeinsam eine Aufgabe lösen ──────────────
INSERT INTO speaking_exam_tasks (provider, level, teil_no, archetype, stimulus_json)
SELECT p.provider, 'B1', p.teil_no, 'PLAN_NEGOTIATE',
       jsonb_build_object('type', 'PLANNING_CARD', 'situation', s.situation, 'prompts', s.prompts)
FROM (VALUES ('GOETHE', 1), ('TELC', 3)) AS p(provider, teil_no)
CROSS JOIN (VALUES
 ('Eine Kollegin aus Ihrem Deutschkurs liegt im Krankenhaus. Sie möchten sie zusammen besuchen.', '["Wann besuchen?","Wie hinkommen?","Was mitbringen?","Wie helfen (Hausaufgaben, Einkaufen)?"]'::jsonb),
 ('Ihr Deutschkurs endet bald. Sie organisieren zusammen eine Abschlussfeier.', '["Wo feiern?","Wann?","Essen und Getränke?","Musik und Programm?","Wer lädt ein?"]'::jsonb),
 ('Ein Freund zieht in eine neue Wohnung. Sie wollen ihm zusammen helfen.', '["An welchem Tag?","Wer bringt ein Auto?","Was muss man kaufen?","Wer organisiert das Essen?"]'::jsonb),
 ('Sie möchten mit Ihrer Lerngruppe ein Wochenende in einer anderen Stadt verbringen.', '["Welche Stadt?","Wie reisen?","Wo übernachten?","Was besichtigen?","Wie viel darf es kosten?"]'::jsonb),
 ('Ein neuer Nachbar ist gerade aus dem Ausland gekommen und kennt niemanden. Sie wollen ihm helfen, sich einzuleben.', '["Was zeigen Sie ihm?","Wann treffen?","Welche Informationen braucht er?","Wer hilft womit?"]'::jsonb),
 ('Sie wollen zusammen einen Flohmarktstand machen, um alte Sachen zu verkaufen.', '["Was verkaufen?","Welcher Markt, welcher Tag?","Wie transportieren?","Wer macht was?"]'::jsonb),
 ('Ihre Lehrerin hat Geburtstag. Der Kurs möchte ihr eine Überraschung machen.', '["Welches Geschenk?","Wie viel Geld pro Person?","Wann und wo übergeben?","Wer sammelt das Geld?"]'::jsonb),
 ('Sie möchten zusammen an einem Sportlauf in Ihrer Stadt teilnehmen.', '["Wann trainieren?","Wo anmelden?","Welche Ausrüstung?","Wie zum Start kommen?"]'::jsonb)
) AS s(situation, prompts);

-- ── Goethe B1 T2 — Ein Thema präsentieren (chọn 1 trong 2; 5 Folien diễn đạt lại, không chép nguyên văn) ──
INSERT INTO speaking_exam_tasks (provider, level, teil_no, archetype, stimulus_json)
SELECT 'GOETHE', 'B1', 2, 'PRESENT',
       jsonb_build_object('type', 'FOLIEN_DECK', 'topic', t.topic,
         'folien', '["Thema vorstellen: Worum geht es? Wie ist der Vortrag aufgebaut?",
                     "Eigene Erfahrung: Was haben Sie selbst erlebt?",
                     "Situation in Ihrem Heimatland mit Beispielen",
                     "Vor- und Nachteile — und Ihre eigene Meinung mit Beispielen",
                     "Schluss: zusammenfassen und sich bei den Zuhörern bedanken"]'::jsonb)
FROM (VALUES
 ('Sollten Kinder ein eigenes Handy haben?'),('Lernen mit dem Computer oder mit Büchern?'),('Mit dem Auto oder mit dem Fahrrad in die Stadt?'),
 ('Essen gehen oder selbst kochen?'),('Urlaub im eigenen Land oder im Ausland?'),('Ist Fernsehen Zeitverschwendung?'),
 ('Sport im Verein oder allein?'),('Wohnen in der Stadt oder auf dem Land?'),('Sind soziale Netzwerke gut für Freundschaften?'),
 ('Sollte man schon als Kind eine Fremdsprache lernen?'),('Online einkaufen oder im Geschäft?'),('Haustiere in der Stadt — ja oder nein?')
) AS t(topic);

-- ── Goethe B1 T3 — Über ein Thema sprechen: partner trình bày TRƯỚC (văn bản B1 có 2–3 lỗi chủ ý), thí sinh nhận xét + hỏi ──
INSERT INTO speaking_exam_tasks (provider, level, teil_no, archetype, stimulus_json) VALUES
('GOETHE','B1',3,'FEEDBACK_FOLLOWUP',$j$ {"type":"PARTNER_PRESENTATION","topic":"Mit dem Fahrrad zur Arbeit?","instruction":"Hören Sie zu. Geben Sie danach eine Rückmeldung (Was war interessant? Was war neu?) und stellen Sie eine Frage.","partnerPresentation":"Mein Thema ist: Mit dem Fahrrad zur Arbeit. Zuerst erzähle ich von mir, dann von meinem Heimatland und am Ende sage ich meine Meinung. Ich fahre seit zwei Jahre mit dem Fahrrad zur Arbeit, das dauert zwanzig Minuten. In meinem Heimatland Vietnam fahren viele Leute mit dem Motorrad, weil die Straßen sind sehr voll. Ein Vorteil vom Fahrrad ist, dass es billig und gesund ist. Ein Nachteil ist das Wetter, wenn es regnet, komme ich nass ins Büro. Ich finde, das Fahrrad ist trotzdem besser als das Auto. Vielen Dank für Ihre Aufmerksamkeit."} $j$),
('GOETHE','B1',3,'FEEDBACK_FOLLOWUP',$j$ {"type":"PARTNER_PRESENTATION","topic":"Lernen mit einer App","instruction":"Hören Sie zu. Geben Sie danach eine Rückmeldung und stellen Sie eine Frage.","partnerPresentation":"Ich möchte über das Lernen mit einer App sprechen. Mein Vortrag hat drei Teile. Ich lerne jeden Tag zehn Minuten Deutsch mit einer App, meistens im Bus. In meinem Heimatland lernen viele junge Leute Englisch mit dem Handy, weil die Kurse sind teuer. Der Vorteil ist, man kann überall lernen. Aber der Nachteil ist, dass man nicht sprechen übt und manchmal ich vergesse die Wörter schnell. Meine Meinung: Eine App ist gut als Hilfe, aber ein Kurs mit Lehrer ist wichtiger. Danke fürs Zuhören."} $j$),
('GOETHE','B1',3,'FEEDBACK_FOLLOWUP',$j$ {"type":"PARTNER_PRESENTATION","topic":"Wohnen in einer WG","instruction":"Hören Sie zu. Geben Sie danach eine Rückmeldung und stellen Sie eine Frage.","partnerPresentation":"Mein Thema heißt Wohnen in einer WG, also in einer Wohngemeinschaft. Ich wohne seit einem Jahr mit zwei andere Studenten zusammen. Wir teilen die Küche und das Bad. In meinem Heimatland wohnen junge Leute normalerweise bei die Eltern, bis sie heiraten. Ein Vorteil ist, dass die Miete billiger ist und man ist nicht allein. Ein Nachteil ist, wenn jemand laut ist oder nicht putzt. Ich denke, eine WG ist eine gute Erfahrung, besonders für Studenten. Vielen Dank."} $j$),
('GOETHE','B1',3,'FEEDBACK_FOLLOWUP',$j$ {"type":"PARTNER_PRESENTATION","topic":"Frühstück — wichtig oder nicht?","instruction":"Hören Sie zu. Geben Sie danach eine Rückmeldung und stellen Sie eine Frage.","partnerPresentation":"Ich spreche heute über das Frühstück. Zuerst meine Erfahrung, dann mein Heimatland, dann meine Meinung. Ich habe früher nie gefrühstückt, weil ich keine Zeit hatte. Jetzt esse ich jeden Morgen ein Brot und trinke einen Kaffee. In meinem Heimatland isst man zum Frühstück oft eine Suppe mit Nudeln, das ist sehr warm und gut. Der Vorteil von einem guten Frühstück ist, dass man mehr Energie hat. Der Nachteil ist nur, man muss früher aufstehen. Ich bin der Meinung, Frühstück ist die wichtigste Mahlzeit. Danke schön."} $j$),
('GOETHE','B1',3,'FEEDBACK_FOLLOWUP',$j$ {"type":"PARTNER_PRESENTATION","topic":"Geschenke kaufen — stressig oder schön?","instruction":"Hören Sie zu. Geben Sie danach eine Rückmeldung und stellen Sie eine Frage.","partnerPresentation":"Mein Thema ist Geschenke kaufen. Ich finde das manchmal stressig, weil ich nie weiß, was die Person mag. Letztes Jahr ich habe für meine Mutter ein Buch gekauft, und sie hat sich sehr gefreut. In meinem Heimatland schenkt man zu Neujahr Geld in einem roten Umschlag. Das ist praktisch, aber nicht sehr persönlich. Ein Vorteil von Geschenken ist, dass man Freude macht. Der Nachteil: Es kostet Zeit und Geld. Ich meine, ein kleines Geschenk mit Liebe ist besser als ein teures. Vielen Dank fürs Zuhören."} $j$),
('GOETHE','B1',3,'FEEDBACK_FOLLOWUP',$j$ {"type":"PARTNER_PRESENTATION","topic":"Sport in der Freizeit","instruction":"Hören Sie zu. Geben Sie danach eine Rückmeldung und stellen Sie eine Frage.","partnerPresentation":"Ich erzähle über Sport in der Freizeit. Mein Vortrag hat drei Teile. Ich spiele zweimal pro Woche Fußball mit Freunden in einem Park. In meinem Heimatland machen die Leute morgens früh Sport auf der Straße, zum Beispiel Tai-Chi oder Badminton. Ein Vorteil ist die Gesundheit und man trifft Leute. Der Nachteil ist, dass man manchmal sich verletzt. Ich glaube, jeder sollte ein bisschen Sport machen, auch wenn er wenig Zeit hat. Danke."} $j$),
('GOETHE','B1',3,'FEEDBACK_FOLLOWUP',$j$ {"type":"PARTNER_PRESENTATION","topic":"Online einkaufen","instruction":"Hören Sie zu. Geben Sie danach eine Rückmeldung und stellen Sie eine Frage.","partnerPresentation":"Mein Thema ist Online einkaufen. Zuerst erzähle ich von mir. Ich kaufe Kleidung und Bücher oft im Internet, weil es ist bequem. Letzte Woche habe ich Schuhe bestellt, aber sie waren zu klein, und ich musste sie zurückschicken. In meinem Heimatland bestellen viele Leute Essen mit dem Handy, das kommt in zwanzig Minuten. Der Vorteil ist, man spart Zeit. Der Nachteil ist, man kann die Sachen nicht anfassen. Meine Meinung ist, für Bücher ist online gut, aber Kleidung kaufe ich lieber im Geschäft. Vielen Dank."} $j$),
('GOETHE','B1',3,'FEEDBACK_FOLLOWUP',$j$ {"type":"PARTNER_PRESENTATION","topic":"Ein Jahr im Ausland","instruction":"Hören Sie zu. Geben Sie danach eine Rückmeldung und stellen Sie eine Frage.","partnerPresentation":"Ich möchte über ein Jahr im Ausland sprechen. Ich bin seit acht Monaten in Deutschland. Am Anfang war alles schwer, die Sprache, das Essen und das Wetter. Jetzt habe ich Freunde und ich verstehe fast alles. In meinem Heimatland gehen viele junge Menschen nach Japan oder Korea, um zu arbeiten. Ein Vorteil vom Ausland ist, dass man selbstständig wird. Ein Nachteil ist, dass man die Familie vermisst. Ich finde, ein Jahr im Ausland sollte jeder Mensch machen. Danke fürs Zuhören."} $j$);

-- ── telc B1 T1 — Kontaktaufnahme ───────────────────────────────────────────────────────────────
INSERT INTO speaking_exam_tasks (provider, level, teil_no, archetype, stimulus_json) VALUES
('TELC','B1',1,'TOPIC_EXCHANGE',$j$ {"type":"CONTACT_CARD","instruction":"Lernen Sie sich kennen. Sprechen Sie über die Themen auf der Karte. Am Ende stellt die Prüferin noch eine Frage.","topics":["Name","Herkunft","Wohnen","Familie","Schule / Studium / Beruf","Auslandserfahrung","Sprachen"]} $j$),
('TELC','B1',1,'TOPIC_EXCHANGE',$j$ {"type":"CONTACT_CARD","instruction":"Lernen Sie sich kennen. Sprechen Sie über die Themen auf der Karte.","topics":["Name","Wohnort und Wohnung","Arbeit oder Ausbildung","Freizeit","Reisen","Deutsch lernen — seit wann, warum?"]} $j$),
('TELC','B1',1,'TOPIC_EXCHANGE',$j$ {"type":"CONTACT_CARD","instruction":"Lernen Sie sich kennen. Sprechen Sie über die Themen auf der Karte.","topics":["Name und Alter","Familie","Beruf","Was machen Sie gern am Wochenende?","Welche Sprachen sprechen Sie?","Pläne für die Zukunft"]} $j$);

-- ── telc B1 T2 — Gespräch über ein Thema: Vorlage A (thí sinh) / Vorlage B (partner, riêng tư), số liệu hư cấu ──
INSERT INTO speaking_exam_tasks (provider, level, teil_no, archetype, stimulus_json) VALUES
('TELC','B1',2,'TOPIC_EXCHANGE',$j$ {"type":"TOPIC_GRAPHIC_PAIR","thema":"Ferien und Reisen","instruction":"Berichten Sie Ihrem Partner, was auf Ihrer Vorlage steht. Hören Sie, was Ihr Partner berichtet. Sprechen Sie dann über Ihre eigenen Erfahrungen und Meinungen.","candidateText":"Fiktive Umfrage: Wohin fahren Deutsche am liebsten in den Urlaub? Die meisten bleiben im eigenen Land oder fahren ans Meer nach Italien und Spanien.","candidateChart":{"title":"Beliebteste Urlaubsziele (fiktiv, in %)","unit":"%","series":[{"label":"Deutschland","value":34},{"label":"Italien","value":18},{"label":"Spanien","value":15},{"label":"Türkei","value":9},{"label":"Andere","value":24}]},"partnerText":"Fiktive Umfrage: Wie verreisen junge Leute? Die meisten fahren mit dem Zug oder dem Auto; immer mehr buchen ihre Reise online.","partnerChart":{"title":"Verkehrsmittel im Urlaub (fiktiv, in %)","unit":"%","series":[{"label":"Auto","value":41},{"label":"Flugzeug","value":27},{"label":"Zug","value":22},{"label":"Bus","value":10}]}} $j$),
('TELC','B1',2,'TOPIC_EXCHANGE',$j$ {"type":"TOPIC_GRAPHIC_PAIR","thema":"Gesund leben","instruction":"Berichten Sie Ihrem Partner, was auf Ihrer Vorlage steht. Hören Sie zu und sprechen Sie dann über Ihre Erfahrungen.","candidateText":"Fiktive Umfrage: Was tun Menschen für ihre Gesundheit? Bewegung und gesundes Essen stehen vorn, aber viele sagen, ihnen fehlt die Zeit.","candidateChart":{"title":"Was tun Sie für Ihre Gesundheit? (fiktiv, in %)","unit":"%","series":[{"label":"Sport","value":48},{"label":"Gesund essen","value":44},{"label":"Genug schlafen","value":31},{"label":"Nichts Besonderes","value":17}]},"partnerText":"Fiktive Umfrage: Wie oft machen Erwachsene Sport? Fast die Hälfte macht seltener als einmal pro Woche Sport.","partnerChart":{"title":"Sport pro Woche (fiktiv, in %)","unit":"%","series":[{"label":"Nie","value":22},{"label":"Seltener als 1x","value":25},{"label":"1–2x","value":33},{"label":"3x und mehr","value":20}]}} $j$),
('TELC','B1',2,'TOPIC_EXCHANGE',$j$ {"type":"TOPIC_GRAPHIC_PAIR","thema":"Medien im Alltag","instruction":"Berichten Sie, was auf Ihrer Vorlage steht, hören Sie Ihrem Partner zu und tauschen Sie sich aus.","candidateText":"Fiktive Umfrage: Wie informieren sich junge Leute über Nachrichten? Das Handy ist die wichtigste Quelle, die Zeitung liest kaum noch jemand.","candidateChart":{"title":"Nachrichtenquelle 18–29 Jahre (fiktiv, in %)","unit":"%","series":[{"label":"Handy / Internet","value":63},{"label":"Fernsehen","value":21},{"label":"Radio","value":10},{"label":"Zeitung","value":6}]},"partnerText":"Fiktive Umfrage: Wie lange sind Menschen täglich am Handy? Viele mehr als drei Stunden.","partnerChart":{"title":"Handyzeit pro Tag (fiktiv, in %)","unit":"%","series":[{"label":"unter 1 Std.","value":12},{"label":"1–3 Std.","value":41},{"label":"3–5 Std.","value":30},{"label":"über 5 Std.","value":17}]}} $j$),
('TELC','B1',2,'TOPIC_EXCHANGE',$j$ {"type":"TOPIC_GRAPHIC_PAIR","thema":"Arbeit und Beruf","instruction":"Berichten Sie, was auf Ihrer Vorlage steht, hören Sie Ihrem Partner zu und tauschen Sie sich aus.","candidateText":"Fiktive Umfrage: Was ist im Beruf am wichtigsten? Nette Kollegen und ein sicherer Arbeitsplatz sind den meisten wichtiger als ein hohes Gehalt.","candidateChart":{"title":"Was ist im Job wichtig? (fiktiv, in %)","unit":"%","series":[{"label":"Nette Kollegen","value":52},{"label":"Sicherer Job","value":47},{"label":"Hohes Gehalt","value":38},{"label":"Kurzer Arbeitsweg","value":29}]},"partnerText":"Fiktive Umfrage: Wie viele Menschen arbeiten von zu Hause? Etwa ein Drittel arbeitet manchmal im Homeoffice.","partnerChart":{"title":"Homeoffice (fiktiv, in %)","unit":"%","series":[{"label":"Nie","value":55},{"label":"Manchmal","value":31},{"label":"Immer","value":14}]}} $j$),
('TELC','B1',2,'TOPIC_EXCHANGE',$j$ {"type":"TOPIC_GRAPHIC_PAIR","thema":"Einkaufen","instruction":"Berichten Sie, was auf Ihrer Vorlage steht, hören Sie Ihrem Partner zu und tauschen Sie sich aus.","candidateText":"Fiktive Umfrage: Wo kaufen Menschen Lebensmittel? Der Supermarkt ist Nummer eins, der Wochenmarkt wird wieder beliebter.","candidateChart":{"title":"Wo kaufen Sie Lebensmittel? (fiktiv, in %)","unit":"%","series":[{"label":"Supermarkt","value":71},{"label":"Discounter","value":58},{"label":"Wochenmarkt","value":19},{"label":"Online","value":9}]},"partnerText":"Fiktive Umfrage: Was kaufen Leute online? Kleidung und Elektronik am häufigsten, Lebensmittel selten.","partnerChart":{"title":"Online gekauft (fiktiv, in %)","unit":"%","series":[{"label":"Kleidung","value":61},{"label":"Elektronik","value":49},{"label":"Bücher","value":37},{"label":"Lebensmittel","value":11}]}} $j$),
('TELC','B1',2,'TOPIC_EXCHANGE',$j$ {"type":"TOPIC_GRAPHIC_PAIR","thema":"Wohnen","instruction":"Berichten Sie, was auf Ihrer Vorlage steht, hören Sie Ihrem Partner zu und tauschen Sie sich aus.","candidateText":"Fiktive Umfrage: Wie wohnen junge Erwachsene? Viele wohnen noch bei den Eltern oder in einer WG, weil Wohnungen teuer sind.","candidateChart":{"title":"Wohnform 20–29 Jahre (fiktiv, in %)","unit":"%","series":[{"label":"Bei den Eltern","value":36},{"label":"WG","value":24},{"label":"Allein","value":22},{"label":"Mit Partner/in","value":18}]},"partnerText":"Fiktive Umfrage: Was ist bei der Wohnung wichtig? Ruhe und gute Verkehrsverbindung stehen ganz oben.","partnerChart":{"title":"Wichtig bei der Wohnung (fiktiv, in %)","unit":"%","series":[{"label":"Ruhige Lage","value":54},{"label":"Gute Verbindung","value":49},{"label":"Balkon","value":33},{"label":"Nähe zur Arbeit","value":28}]}} $j$),
('TELC','B1',2,'TOPIC_EXCHANGE',$j$ {"type":"TOPIC_GRAPHIC_PAIR","thema":"Lernen und Sprachen","instruction":"Berichten Sie, was auf Ihrer Vorlage steht, hören Sie Ihrem Partner zu und tauschen Sie sich aus.","candidateText":"Fiktive Umfrage: Warum lernen Menschen eine Fremdsprache? Beruf und Reisen sind die häufigsten Gründe.","candidateChart":{"title":"Gründe für das Sprachenlernen (fiktiv, in %)","unit":"%","series":[{"label":"Beruf","value":46},{"label":"Reisen","value":39},{"label":"Familie / Partner","value":21},{"label":"Spaß","value":18}]},"partnerText":"Fiktive Umfrage: Wie lernen Menschen am liebsten? Im Kurs mit anderen, aber Apps holen auf.","partnerChart":{"title":"Lieblingsmethode (fiktiv, in %)","unit":"%","series":[{"label":"Sprachkurs","value":44},{"label":"App","value":31},{"label":"Filme / Musik","value":15},{"label":"Tandem","value":10}]}} $j$),
('TELC','B1',2,'TOPIC_EXCHANGE',$j$ {"type":"TOPIC_GRAPHIC_PAIR","thema":"Freizeit","instruction":"Berichten Sie, was auf Ihrer Vorlage steht, hören Sie Ihrem Partner zu und tauschen Sie sich aus.","candidateText":"Fiktive Umfrage: Was machen Menschen abends am liebsten? Fernsehen und Handy liegen vorn, aber viele treffen auch Freunde.","candidateChart":{"title":"Freizeit am Abend (fiktiv, in %)","unit":"%","series":[{"label":"Fernsehen / Serien","value":57},{"label":"Handy / Internet","value":49},{"label":"Freunde treffen","value":35},{"label":"Lesen","value":22}]},"partnerText":"Fiktive Umfrage: Wie viel Freizeit haben Berufstätige pro Tag? Die meisten zwei bis vier Stunden.","partnerChart":{"title":"Freizeit pro Tag (fiktiv, in %)","unit":"%","series":[{"label":"unter 2 Std.","value":27},{"label":"2–4 Std.","value":48},{"label":"über 4 Std.","value":25}]}} $j$);
