-- Đợt 7 — sửa FORM phần thi Nói telc B1 (15/09/2026).
--
-- Hai việc, đều là lỗi form chứ không phải thiếu đề:
--
-- S3. Cả 8 thẻ Teil 2 hiện có đều là TOPIC_GRAPHIC_PAIR (có biểu đồ). Vorlage của đề thật thường
--     là một ĐOẠN VĂN ngắn, số liệu chỉ thỉnh thoảng — luyện toàn biểu đồ là học tủ kỹ năng đọc
--     biểu đồ. Thêm 8 thẻ TOPIC_TEXT_PAIR để trộn khoảng 50/50.
--
-- S6′. Thẻ Teil 3 của telc đang DÙNG CHUNG với Goethe B1 Teil 1 (V279 chèn bằng CROSS JOIN cho cả
--      hai hệ), nên sửa thẻ telc là sửa luôn đề Goethe. Và telc đòi nói rõ AI LÀM VIỆC GÌ
--      („wer welche Aufgaben übernimmt") — ở thẻ dùng chung thì điều đó chỉ là tuỳ thẻ.
--      Tách hẳn: xoá các thẻ Teil 3 dùng chung của telc, thay bằng bộ TASK_SITUATION riêng mà
--      MỌI thẻ đều có một prompt phân công việc. Thẻ của Goethe (provider GOETHE, teil 1) giữ nguyên.
--
-- Phiên đang thi không bị ảnh hưởng: đề đã rút nằm trong `speaking_exam_sessions.plan_json`,
-- không đọc lại bảng này.

-- ── S3: Vorlage dạng đoạn văn, không biểu đồ ─────────────────────────────────────────────────
INSERT INTO speaking_exam_tasks (provider, level, teil_no, archetype, stimulus_json) VALUES
('TELC','B1',2,'TOPIC_EXCHANGE',$j$ {"type":"TOPIC_TEXT_PAIR","thema":"Wohnen in der Stadt","instruction":"Berichten Sie Ihrem Partner kurz, welche Informationen Sie zum Thema vorliegen haben. Hören Sie zu, erzählen Sie dann von Ihren eigenen Erfahrungen und geben Sie Gründe an. Reagieren Sie auf die Vorstellungen Ihres Partners.","candidateText":"In vielen deutschen Städten steigen die Mieten seit Jahren. Junge Leute ziehen deshalb öfter in Wohngemeinschaften oder in Orte am Stadtrand, von wo aus sie mit dem Zug zur Arbeit fahren.","partnerText":"Auf dem Land stehen dagegen viele Wohnungen leer. Manche Gemeinden bieten günstige Häuser an, wenn Familien dort bleiben und die Häuser renovieren."} $j$),
('TELC','B1',2,'TOPIC_EXCHANGE',$j$ {"type":"TOPIC_TEXT_PAIR","thema":"Essen und Einkaufen","instruction":"Berichten Sie kurz, was auf Ihrer Vorlage steht. Erzählen Sie dann von Ihren eigenen Erfahrungen mit Gründen und reagieren Sie auf Ihren Partner.","candidateText":"Immer mehr Menschen kaufen Lebensmittel direkt beim Bauern oder auf dem Wochenmarkt. Sie sagen, das Obst schmecke besser und man wisse, woher es komme.","partnerText":"Gleichzeitig bestellen viele ihren Wocheneinkauf im Internet. Vor allem Berufstätige mit Kindern sparen so Zeit, zahlen aber eine Liefergebühr."} $j$),
('TELC','B1',2,'TOPIC_EXCHANGE',$j$ {"type":"TOPIC_TEXT_PAIR","thema":"Sprachen lernen","instruction":"Berichten Sie kurz von Ihrer Vorlage, dann von Ihren eigenen Erfahrungen mit Gründen. Gehen Sie auf Ihren Partner ein.","candidateText":"Viele Erwachsene lernen eine Fremdsprache heute mit Apps auf dem Handy. Sie üben kurz in der Bahn oder in der Pause, oft nur zehn Minuten am Tag.","partnerText":"Andere gehen lieber in einen Kurs an der Volkshochschule. Sie sagen, in der Gruppe spreche man mehr und bleibe eher dabei, weil man feste Termine habe."} $j$),
('TELC','B1',2,'TOPIC_EXCHANGE',$j$ {"type":"TOPIC_TEXT_PAIR","thema":"Freizeit und Sport","instruction":"Berichten Sie kurz, hören Sie zu, erzählen Sie von sich mit Gründen und reagieren Sie auf Ihren Partner.","candidateText":"In vielen Städten gibt es inzwischen kostenlose Sportgeräte im Park. Wer keine Zeit oder kein Geld für ein Fitnessstudio hat, trainiert dort morgens oder abends.","partnerText":"Sportvereine klagen dagegen über zu wenige Mitglieder. Junge Leute wollen sich nicht für ein ganzes Jahr anmelden, sondern lieber spontan entscheiden."} $j$),
('TELC','B1',2,'TOPIC_EXCHANGE',$j$ {"type":"TOPIC_TEXT_PAIR","thema":"Arbeit und Ausbildung","instruction":"Berichten Sie kurz von Ihrer Vorlage, erzählen Sie dann von Ihren Erfahrungen mit Gründen und gehen Sie auf Ihren Partner ein.","candidateText":"Handwerksbetriebe in Deutschland suchen dringend Auszubildende. Viele Jugendliche gehen lieber zur Universität, obwohl man im Handwerk schon während der Ausbildung Geld verdient.","partnerText":"Manche Firmen bieten deshalb neue Wege an: eine Ausbildung mit Studium daneben, oder einen Betrieb, der die Fahrkarte und das Werkzeug bezahlt."} $j$),
('TELC','B1',2,'TOPIC_EXCHANGE',$j$ {"type":"TOPIC_TEXT_PAIR","thema":"Umwelt im Alltag","instruction":"Berichten Sie kurz, hören Sie Ihrem Partner zu und tauschen Sie Erfahrungen und Meinungen mit Gründen aus.","candidateText":"In vielen Geschäften kann man Flaschen und Gläser selbst füllen und bringt eigene Behälter mit. Kunden sagen, so entstehe deutlich weniger Müll.","partnerText":"Kritiker meinen, das koste Zeit und sei teurer. Für Familien mit wenig Geld sei es leichter, weiter im Supermarkt einzukaufen."} $j$),
('TELC','B1',2,'TOPIC_EXCHANGE',$j$ {"type":"TOPIC_TEXT_PAIR","thema":"Reisen","instruction":"Berichten Sie kurz von Ihrer Vorlage, dann von Ihren eigenen Erfahrungen mit Gründen; reagieren Sie auf Ihren Partner.","candidateText":"Immer mehr Leute verbringen den Urlaub im eigenen Land. Sie nennen als Gründe die Kosten, die kurze Anreise und dass man kein Flugzeug nehmen muss.","partnerText":"Andere sparen das ganze Jahr für eine weite Reise. Sie sagen, man lerne dabei eine andere Sprache und andere Gewohnheiten viel besser kennen."} $j$),
('TELC','B1',2,'TOPIC_EXCHANGE',$j$ {"type":"TOPIC_TEXT_PAIR","thema":"Nachbarschaft","instruction":"Berichten Sie kurz, erzählen Sie dann von Ihren Erfahrungen mit Gründen und gehen Sie auf die Vorstellungen Ihres Partners ein.","candidateText":"In manchen Häusern gibt es ein gemeinsames Regal im Flur. Wer etwas nicht mehr braucht, stellt es dorthin; die Nachbarn nehmen es mit.","partnerText":"Nicht alle finden das gut. Manche stören sich an Unordnung im Treppenhaus und möchten lieber feste Regeln oder gar kein Regal."} $j$);

-- ── S6′: Teil 3 có bộ thẻ riêng, MỌI thẻ đều bắt buộc phân công việc ─────────────────────────
DELETE FROM speaking_exam_tasks
 WHERE provider = 'TELC' AND level = 'B1' AND teil_no = 3
   AND stimulus_json->>'type' = 'PLANNING_CARD';

INSERT INTO speaking_exam_tasks (provider, level, teil_no, archetype, stimulus_json) VALUES
('TELC','B1',3,'PLAN_NEGOTIATE',$j$ {"type":"TASK_SITUATION","situation":"Ihre Deutschlehrerin geht in Rente. Der Kurs möchte sich gemeinsam von ihr verabschieden und dafür eine kleine Feier am letzten Kurstag vorbereiten.","prompts":["Was soll es geben (Essen, Musik, Geschenk)?","Wann und wo genau?","Wie viel Geld gibt jeder?","Wer übernimmt welche Aufgabe?"]} $j$),
('TELC','B1',3,'PLAN_NEGOTIATE',$j$ {"type":"TASK_SITUATION","situation":"Ein neuer Kollege kommt nächste Woche aus dem Ausland in Ihre Firma. Sie beide sollen ihm die erste Woche erleichtern.","prompts":["Was zeigen Sie ihm zuerst?","Wann treffen Sie sich mit ihm?","Welche Informationen braucht er sofort?","Wer übernimmt welche Aufgabe?"]} $j$),
('TELC','B1',3,'PLAN_NEGOTIATE',$j$ {"type":"TASK_SITUATION","situation":"Im Haus, in dem Sie beide wohnen, ist der Hof sehr ungepflegt. Sie wollen mit den Nachbarn einen Aufräumtag organisieren.","prompts":["An welchem Tag und wie lange?","Welche Geräte werden gebraucht?","Wie informieren Sie die Nachbarn?","Wer übernimmt welche Aufgabe?"]} $j$),
('TELC','B1',3,'PLAN_NEGOTIATE',$j$ {"type":"TASK_SITUATION","situation":"Eine Freundin aus Ihrem Kurs hat sich das Bein gebrochen und kann drei Wochen nicht einkaufen gehen. Sie beide möchten ihr helfen.","prompts":["Wie oft besuchen Sie sie?","Wer kauft ein und wann?","Was braucht sie außerdem?","Wer übernimmt welche Aufgabe?"]} $j$),
('TELC','B1',3,'PLAN_NEGOTIATE',$j$ {"type":"TASK_SITUATION","situation":"Ihr Sprachkurs möchte am Wochenende einen Ausflug in eine andere Stadt machen. Sie beide sollen ihn planen.","prompts":["Welche Stadt und warum?","Wie fahren Sie hin?","Was besichtigen Sie dort?","Wer übernimmt welche Aufgabe?"]} $j$),
('TELC','B1',3,'PLAN_NEGOTIATE',$j$ {"type":"TASK_SITUATION","situation":"In Ihrem Stadtteil findet ein Sommerfest statt. Ihr Kurs darf einen Stand mit Essen aus verschiedenen Ländern anbieten.","prompts":["Welche Gerichte bieten Sie an?","Woher kommen Tische und Geschirr?","Wie viel soll alles kosten?","Wer übernimmt welche Aufgabe?"]} $j$),
('TELC','B1',3,'PLAN_NEGOTIATE',$j$ {"type":"TASK_SITUATION","situation":"Ein Freund von Ihnen beiden zieht am Samstag in eine neue Wohnung im dritten Stock und hat niemanden, der ihm hilft.","prompts":["Wann fangen Sie an?","Wer organisiert ein Auto?","Was muss vorher gekauft werden?","Wer übernimmt welche Aufgabe?"]} $j$),
('TELC','B1',3,'PLAN_NEGOTIATE',$j$ {"type":"TASK_SITUATION","situation":"Ihre Lerngruppe will vor der Prüfung zwei Wochen lang zusammen üben. Sie beide sollen den Plan machen.","prompts":["An welchen Tagen und wie lange?","Wo treffen Sie sich?","Welche Prüfungsteile üben Sie wann?","Wer übernimmt welche Aufgabe?"]} $j$);
