-- Gói D — thi Nói telc B1 đúng bản chính thức 2020 (17/09/2026).
--
-- Nguồn đối chiếu: Bewertungsbogen M10 + Prüferblätter của telc Deutsch B1 Übungstest 1 (2020),
-- so với 10 Test của sách ZD (2012). Bốn việc, đều là DỮ LIỆU, không đổi schema:
--
--   D1. Rubric Nói (V277) ghi bậc C = 2 (max 4) và 4 (max 8) — nội suy, có ghi chú "approximation".
--       Bản chính thức: Kriterium 1–3 = 4/3/1/0 (Teil 1) và 8/6/2/0 (Teil 2–3); Kriterium 4
--       Aussprache = 3/2/1/0 và 6/4/2/0 (đã đúng). Sửa đúng ô C, xoá "approximation", ghi nguồn.
--       Phiên đã chấm không đổi (điểm nằm trong speaking_exam_results); phiên đang thi chấm bằng
--       rubric lúc chấm ⇒ dùng bảng mới, đúng ý.
--   D2. Teil 2 „Gespräch über ein Thema" từ 2020 KHÔNG còn là biểu đồ/đoạn văn mà là HAI Ý KIẾN
--       TRÁI CHIỀU có tên/tuổi/nghề (kho 40 chủ đề đang ra xác nhận). Thêm 8 thẻ TOPIC_OPINION_PAIR:
--       `candidateOpinion` (thí sinh thấy) và `partnerOpinion` (riêng của bạn thi AI — tiền tố
--       partner* nên client không bao giờ nhận). Nhân vật và ý kiến SOẠN GỐC (repo PUBLIC).
--   D3. Teil 3: thêm 6 TASK_SITUATION theo danh mục tình huống đang ra, Zettel 3–5 mục; MỌI thẻ
--       Teil 3 (cũ và mới) có `instruction` bốn bước của đề thật (entscheiden → vortragen und
--       begründen → reagieren → sich einigen, wer welche Aufgabe übernimmt).
--   D4. Teil 1: 3 CONTACT_CARD theo thẻ 2020 („Wo Sie Deutsch gelernt haben", „Sprachen (welche?
--       wie lange? warum?)") + `partnerExtraQuestions`: câu hỏi thêm của giám khảo cuối Teil 1,
--       chỉ AI thấy (đề thật in ở Prüferblatt, thí sinh không biết trước). Thẻ cũ giữ nguyên.
--
-- 🪤 Không viết chuỗi đô-la + ngoặc nhọn (Flyway placeholder); sau $j$ phải có dấu cách.

-- ── D1: bậc C đúng bản chính thức ────────────────────────────────────────────────────────────
UPDATE speaking_exam_blueprints b
SET rubric_json = jsonb_set(
        b.rubric_json - 'approximation',
        '{parts}',
        (
            SELECT jsonb_agg(
                       jsonb_set(part, '{criteria}', (
                           SELECT jsonb_agg(
                                      CASE
                                          WHEN (crit->>'max')::numeric = 4 THEN jsonb_set(crit, '{bandPoints,C}', '1'::jsonb)
                                          WHEN (crit->>'max')::numeric = 8 THEN jsonb_set(crit, '{bandPoints,C}', '2'::jsonb)
                                          ELSE crit
                                      END ORDER BY cord)
                           FROM jsonb_array_elements(part->'criteria') WITH ORDINALITY AS c(crit, cord)
                       )) ORDER BY pord)
            FROM jsonb_array_elements(b.rubric_json->'parts') WITH ORDINALITY AS p(part, pord)
        )
    ) || jsonb_build_object('source', 'Bewertungsbogen M10, telc Deutsch B1 Übungstest 1 (2020): Kriterium 1-3 = 4/3/1/0 bzw. 8/6/2/0; Kriterium 4 = 3/2/1/0 bzw. 6/4/2/0')
WHERE b.provider = 'TELC' AND b.level = 'B1';

-- ── D2: Teil 2 — hai ý kiến trái chiều (dạng 2020) ───────────────────────────────────────────
INSERT INTO speaking_exam_tasks (provider, level, teil_no, archetype, stimulus_json) VALUES
('TELC','B1',2,'TOPIC_EXCHANGE',$j$ {"type":"TOPIC_OPINION_PAIR","thema":"Ein eigenes Smartphone für Kinder","instruction":"Sie haben eine Meinung zum Thema bekommen. Berichten Sie Ihrem Partner oder Ihrer Partnerin kurz, was diese Person meint. Erzählen Sie dann von Ihren eigenen Erfahrungen und sagen Sie, was Sie selbst denken. Reagieren Sie auf das, was Ihr Partner oder Ihre Partnerin sagt.","candidateOpinion":{"name":"Miriam Falk","age":41,"job":"Erzieherin","quote":"Meine Tochter hat mit neun ihr erstes Handy bekommen, und ich finde das richtig. Sie kann mich anrufen, wenn der Bus nicht kommt, und wir haben klare Regeln: abends bleibt das Handy in der Küche. Kinder lernen den Umgang nur, wenn sie ihn üben dürfen."},"partnerOpinion":{"name":"Jonas Brandt","age":29,"job":"Softwareentwickler","quote":"Ich arbeite mit Apps und weiß, wie sie gemacht sind: Man soll möglichst lange dranbleiben. Ein Kind kann sich dagegen nicht wehren. Vor zwölf braucht niemand ein eigenes Smartphone – ein einfaches Handy zum Telefonieren reicht völlig."}} $j$),
('TELC','B1',2,'TOPIC_EXCHANGE',$j$ {"type":"TOPIC_OPINION_PAIR","thema":"Im Internet bestellen oder im Geschäft kaufen","instruction":"Sie haben eine Meinung zum Thema bekommen. Berichten Sie Ihrem Partner oder Ihrer Partnerin kurz, was diese Person meint. Erzählen Sie dann von Ihren eigenen Erfahrungen und sagen Sie, was Sie selbst denken. Reagieren Sie auf das, was Ihr Partner oder Ihre Partnerin sagt.","candidateOpinion":{"name":"Halil Demir","age":36,"job":"Busfahrer","quote":"Ich arbeite im Schichtdienst, und wenn ich frei habe, sind die Geschäfte oft schon zu. Deshalb bestelle ich fast alles im Internet – Schuhe, Werkzeug, sogar Kaffee. Es kommt am nächsten Tag, und wenn es nicht passt, schicke ich es zurück."},"partnerOpinion":{"name":"Renate Schulz","age":58,"job":"Buchhändlerin","quote":"Ich möchte Dinge anfassen und jemanden fragen können, bevor ich Geld ausgebe. Außerdem stirbt unsere Innenstadt, wenn alle nur noch online bestellen. Die vielen Pakete und Rücksendungen sind auch schlecht für die Umwelt."}} $j$),
('TELC','B1',2,'TOPIC_EXCHANGE',$j$ {"type":"TOPIC_OPINION_PAIR","thema":"Mit dem Auto oder mit Bus und Bahn","instruction":"Sie haben eine Meinung zum Thema bekommen. Berichten Sie Ihrem Partner oder Ihrer Partnerin kurz, was diese Person meint. Erzählen Sie dann von Ihren eigenen Erfahrungen und sagen Sie, was Sie selbst denken. Reagieren Sie auf das, was Ihr Partner oder Ihre Partnerin sagt.","candidateOpinion":{"name":"Katrin Vogel","age":33,"job":"Krankenpflegerin","quote":"Meine Frühschicht beginnt um sechs, da fährt bei uns noch kein Bus. Ohne Auto könnte ich meinen Beruf gar nicht machen. Ich verstehe die Kritik, aber solange Bus und Bahn nachts und am Wochenende so selten fahren, bleibe ich beim Auto."},"partnerOpinion":{"name":"Samuel Okafor","age":24,"job":"Student","quote":"Ich habe kein Auto und vermisse auch keins. Mit dem Semesterticket fahre ich überallhin, in der Bahn kann ich lesen oder schlafen, und ich muss nie einen Parkplatz suchen. Ein Auto kostet jeden Monat mehrere hundert Euro – das Geld gebe ich lieber für Reisen aus."}} $j$),
('TELC','B1',2,'TOPIC_EXCHANGE',$j$ {"type":"TOPIC_OPINION_PAIR","thema":"Wohnen in der Stadt oder auf dem Land","instruction":"Sie haben eine Meinung zum Thema bekommen. Berichten Sie Ihrem Partner oder Ihrer Partnerin kurz, was diese Person meint. Erzählen Sie dann von Ihren eigenen Erfahrungen und sagen Sie, was Sie selbst denken. Reagieren Sie auf das, was Ihr Partner oder Ihre Partnerin sagt.","candidateOpinion":{"name":"Peter Lindner","age":47,"job":"Tischler","quote":"Wir sind vor fünf Jahren aufs Land gezogen und haben es nie bereut. Die Kinder spielen draußen, die Nachbarn helfen sich, und die Miete ist halb so hoch wie in der Stadt. Ja, man braucht ein Auto – aber die Ruhe am Abend ist mit Geld nicht zu bezahlen."},"partnerOpinion":{"name":"Aylin Kaya","age":31,"job":"Grafikdesignerin","quote":"Ich brauche die Stadt: Kino, Konzerte, Freunde, die spontan vorbeikommen. Auf dem Land fährt abends nichts mehr, und ohne Auto ist man verloren. Meine Wohnung ist klein und teuer, aber ich bin in zehn Minuten überall – das ist mir wichtiger als ein Garten."}} $j$),
('TELC','B1',2,'TOPIC_EXCHANGE',$j$ {"type":"TOPIC_OPINION_PAIR","thema":"Haustiere in der Wohnung","instruction":"Sie haben eine Meinung zum Thema bekommen. Berichten Sie Ihrem Partner oder Ihrer Partnerin kurz, was diese Person meint. Erzählen Sie dann von Ihren eigenen Erfahrungen und sagen Sie, was Sie selbst denken. Reagieren Sie auf das, was Ihr Partner oder Ihre Partnerin sagt.","candidateOpinion":{"name":"Sophie Berger","age":27,"job":"Verkäuferin","quote":"Seit ich meinen Hund habe, gehe ich jeden Tag raus, auch bei Regen, und ich habe im Park mehr Leute kennengelernt als in zwei Jahren davor. Ein Tier gibt dem Tag eine Struktur. Klar kostet es Zeit und Geld, aber es macht mich einfach glücklich."},"partnerOpinion":{"name":"Markus Weiß","age":52,"job":"Steuerberater","quote":"Ich finde Tiere in einer kleinen Stadtwohnung nicht richtig. Ein Hund muss stundenlang allein warten, während man arbeitet, und im Urlaub weiß man nicht, wohin mit ihm. Wer wirklich Zeit hat, gut – aber die meisten haben sie nicht."}} $j$),
('TELC','B1',2,'TOPIC_EXCHANGE',$j$ {"type":"TOPIC_OPINION_PAIR","thema":"Geld sparen oder Geld ausgeben","instruction":"Sie haben eine Meinung zum Thema bekommen. Berichten Sie Ihrem Partner oder Ihrer Partnerin kurz, was diese Person meint. Erzählen Sie dann von Ihren eigenen Erfahrungen und sagen Sie, was Sie selbst denken. Reagieren Sie auf das, was Ihr Partner oder Ihre Partnerin sagt.","candidateOpinion":{"name":"Lukas Meier","age":22,"job":"Auszubildender","quote":"Ich verdiene noch nicht viel, aber was ich habe, gebe ich für Konzerte und Reisen mit Freunden aus. Diese Jahre kommen nicht zurück. Sparen kann ich später, wenn ich richtig verdiene – jetzt will ich etwas erleben."},"partnerOpinion":{"name":"Ingrid Hoffmann","age":63,"job":"Rentnerin","quote":"Ich habe mein ganzes Leben lang jeden Monat etwas zurückgelegt, auch wenn es nur zwanzig Euro waren. Als die Waschmaschine kaputt war und als mein Mann krank wurde, war ich froh darüber. Wer nichts spart, ist beim ersten Problem sofort in Schwierigkeiten."}} $j$),
('TELC','B1',2,'TOPIC_EXCHANGE',$j$ {"type":"TOPIC_OPINION_PAIR","thema":"Sport im Fitnessstudio oder draußen","instruction":"Sie haben eine Meinung zum Thema bekommen. Berichten Sie Ihrem Partner oder Ihrer Partnerin kurz, was diese Person meint. Erzählen Sie dann von Ihren eigenen Erfahrungen und sagen Sie, was Sie selbst denken. Reagieren Sie auf das, was Ihr Partner oder Ihre Partnerin sagt.","candidateOpinion":{"name":"Daniela Roth","age":38,"job":"Bürokauffrau","quote":"Ich gehe dreimal pro Woche ins Fitnessstudio, direkt nach der Arbeit. Dort ist es egal, ob es regnet oder dunkel ist, die Geräte stehen bereit, und ein Trainer zeigt mir, was ich falsch mache. Der Beitrag ist für mich gut angelegtes Geld."},"partnerOpinion":{"name":"Tom Krüger","age":45,"job":"Postbote","quote":"Ich bin den ganzen Tag draußen und laufe abends noch eine Runde im Park – kostenlos, an der frischen Luft, und ich sehe die Jahreszeiten. Im Fitnessstudio schauen alle auf ihr Handy und atmen dieselbe Luft. Das ist nichts für mich."}} $j$),
('TELC','B1',2,'TOPIC_EXCHANGE',$j$ {"type":"TOPIC_OPINION_PAIR","thema":"Den Führerschein so früh wie möglich machen","instruction":"Sie haben eine Meinung zum Thema bekommen. Berichten Sie Ihrem Partner oder Ihrer Partnerin kurz, was diese Person meint. Erzählen Sie dann von Ihren eigenen Erfahrungen und sagen Sie, was Sie selbst denken. Reagieren Sie auf das, was Ihr Partner oder Ihre Partnerin sagt.","candidateOpinion":{"name":"Nadine Schäfer","age":19,"job":"Abiturientin","quote":"Ich habe mit siebzehn angefangen und bin ein Jahr lang mit meiner Mutter neben mir gefahren. Jetzt fahre ich sicher und kann zum Nebenjob und zu Freunden im Nachbardorf fahren. Je früher man anfängt, desto leichter lernt man es."},"partnerOpinion":{"name":"Ahmed Saleh","age":40,"job":"Taxifahrer","quote":"Ein Führerschein kostet heute über dreitausend Euro, und viele junge Leute in der Stadt brauchen ihn dann jahrelang nicht. Mit achtzehn sind manche auch noch zu unvorsichtig – ich sehe das jeden Tag im Verkehr. Man kann ihn später immer noch machen."}} $j$);

-- ── D3: Teil 3 — sáu tình huống mới, Zettel 3–5 mục; bốn bước của đề thật trên mọi thẻ ─────
INSERT INTO speaking_exam_tasks (provider, level, teil_no, archetype, stimulus_json) VALUES
('TELC','B1',3,'PLAN_NEGOTIATE',$j$ {"type":"TASK_SITUATION","situation":"Sie beide möchten am Sonntag mit einigen Leuten aus dem Deutschkurs einen Fahrradausflug machen.","instruction":"Entscheiden Sie zuerst, was zu tun ist. Machen Sie Vorschläge und begründen Sie sie. Reagieren Sie auf die Vorschläge Ihres Partners oder Ihrer Partnerin. Einigen Sie sich, wer welche Aufgabe übernimmt.","prompts":["Wohin und wie weit?","Was nehmen Sie mit?","Was machen Sie bei schlechtem Wetter?","Wer übernimmt welche Aufgabe?"]} $j$),
('TELC','B1',3,'PLAN_NEGOTIATE',$j$ {"type":"TASK_SITUATION","situation":"Sie beide wollen für vier Freunde einen Kochabend organisieren – jeder soll etwas aus seinem Land probieren.","instruction":"Entscheiden Sie zuerst, was zu tun ist. Machen Sie Vorschläge und begründen Sie sie. Reagieren Sie auf die Vorschläge Ihres Partners oder Ihrer Partnerin. Einigen Sie sich, wer welche Aufgabe übernimmt.","prompts":["Was wird gekocht?","Wo und wann?","Wer übernimmt welche Aufgabe?"]} $j$),
('TELC','B1',3,'PLAN_NEGOTIATE',$j$ {"type":"TASK_SITUATION","situation":"Eine Kollegin verlässt nächste Woche die Firma. Sie beide sollen für sie eine kleine Abschiedsparty vorbereiten.","instruction":"Entscheiden Sie zuerst, was zu tun ist. Machen Sie Vorschläge und begründen Sie sie. Reagieren Sie auf die Vorschläge Ihres Partners oder Ihrer Partnerin. Einigen Sie sich, wer welche Aufgabe übernimmt.","prompts":["Wann und wo?","Geschenk?","Essen und Getränke?","Wer informiert die anderen Kollegen?","Wer übernimmt welche Aufgabe?"]} $j$),
('TELC','B1',3,'PLAN_NEGOTIATE',$j$ {"type":"TASK_SITUATION","situation":"Ihr Deutschkurs möchte einen Spieleabend machen, damit sich alle besser kennenlernen. Sie beide planen ihn.","instruction":"Entscheiden Sie zuerst, was zu tun ist. Machen Sie Vorschläge und begründen Sie sie. Reagieren Sie auf die Vorschläge Ihres Partners oder Ihrer Partnerin. Einigen Sie sich, wer welche Aufgabe übernimmt.","prompts":["Welche Spiele?","Wo trifft man sich?","Etwas zu essen?","Wer übernimmt welche Aufgabe?"]} $j$),
('TELC','B1',3,'PLAN_NEGOTIATE',$j$ {"type":"TASK_SITUATION","situation":"Sie wohnen zusammen in einer Wohngemeinschaft. Der Balkon ist leer, und Sie beide möchten ihn im Frühling bepflanzen.","instruction":"Entscheiden Sie zuerst, was zu tun ist. Machen Sie Vorschläge und begründen Sie sie. Reagieren Sie auf die Vorschläge Ihres Partners oder Ihrer Partnerin. Einigen Sie sich, wer welche Aufgabe übernimmt.","prompts":["Welche Pflanzen – Blumen, Gemüse, Kräuter?","Wie viel Geld?","Wer gießt im Urlaub?","Wer übernimmt welche Aufgabe?"]} $j$),
('TELC','B1',3,'PLAN_NEGOTIATE',$j$ {"type":"TASK_SITUATION","situation":"Ein Freund von Ihnen beiden liegt nach einer Operation zu Hause und langweilt sich. Sie wollen bei ihm einen Filmabend organisieren.","instruction":"Entscheiden Sie zuerst, was zu tun ist. Machen Sie Vorschläge und begründen Sie sie. Reagieren Sie auf die Vorschläge Ihres Partners oder Ihrer Partnerin. Einigen Sie sich, wer welche Aufgabe übernimmt.","prompts":["Welcher Film?","Wann?","Wen laden Sie noch ein?","Wer übernimmt welche Aufgabe?"]} $j$);

-- Thẻ Teil 3 cũ (V326) thiếu câu lệnh bốn bước ⇒ bổ sung tại chỗ; thẻ đã có instruction giữ nguyên.
UPDATE speaking_exam_tasks
SET stimulus_json = jsonb_set(stimulus_json, '{instruction}',
        '"Entscheiden Sie zuerst, was zu tun ist. Machen Sie Vorschläge und begründen Sie sie. Reagieren Sie auf die Vorschläge Ihres Partners oder Ihrer Partnerin. Einigen Sie sich, wer welche Aufgabe übernimmt."'::jsonb)
WHERE provider = 'TELC' AND level = 'B1' AND teil_no = 3
  AND stimulus_json->>'type' = 'TASK_SITUATION'
  AND (stimulus_json->>'instruction') IS NULL;

-- ── D4: Teil 1 — thẻ 2020: nơi học tiếng Đức, ngôn ngữ; câu hỏi thêm chỉ giám khảo biết ───────
INSERT INTO speaking_exam_tasks (provider, level, teil_no, archetype, stimulus_json) VALUES
('TELC','B1',1,'TOPIC_EXCHANGE',$j$ {"type":"CONTACT_CARD","instruction":"Lernen Sie Ihren Partner oder Ihre Partnerin kennen. Sprechen Sie über die Punkte auf der Karte. Am Ende stellt die Prüferin oder der Prüfer noch eine Frage.","topics":["Name","Wo Sie wohnen","Familie","Beruf oder Ausbildung","Wo Sie Deutsch gelernt haben","Sprachen (welche? wie lange? warum?)"],"partnerExtraQuestions":["Was machen Sie am Wochenende am liebsten?","Welche Hobbys haben Sie?"]} $j$),
('TELC','B1',1,'TOPIC_EXCHANGE',$j$ {"type":"CONTACT_CARD","instruction":"Lernen Sie Ihren Partner oder Ihre Partnerin kennen. Sprechen Sie über die Punkte auf der Karte. Am Ende stellt die Prüferin oder der Prüfer noch eine Frage.","topics":["Name und Alter","Herkunft","Wohnung und Wohnort","Arbeit oder Studium","Wo Sie Deutsch gelernt haben","Sprachen (welche? wie lange? warum?)"],"partnerExtraQuestions":["Wie sieht ein normaler Tag bei Ihnen aus?","Was machen Sie in Ihrer Freizeit?"]} $j$),
('TELC','B1',1,'TOPIC_EXCHANGE',$j$ {"type":"CONTACT_CARD","instruction":"Lernen Sie Ihren Partner oder Ihre Partnerin kennen. Sprechen Sie über die Punkte auf der Karte. Am Ende stellt die Prüferin oder der Prüfer noch eine Frage.","topics":["Name","Familie","Wohnort","Beruf oder Ausbildung","Wo und wie lange Sie Deutsch gelernt haben","Sprachen (welche? wie lange? warum?)"],"partnerExtraQuestions":["Was haben Sie letztes Wochenende gemacht?","Welchen Sport oder welche Musik mögen Sie?"]} $j$);
