// Generates the legal page content modules (src/content/legal/*.ts) from the markdown
// templates in plans/appstore/. Run:  node scripts/gen-legal.mjs
//
// Fill the constants below when finalizing. The pages render whatever these produce, so there are
// NO literal [[placeholders]] left on the public /privacy, /terms, /support pages.
//
// ⚠️ BEFORE APP STORE SUBMISSION: set LEGAL_NAME_EN / LEGAL_NAME_VI to your REGISTERED LEGAL NAME —
// it must match the name on your Apple individual account (App Store "seller"), W-8BEN and the Paid
// Apps Agreement. The current value is an interim identifier used while that name is finalized.

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const SRC_DIR = path.resolve(HERE, '../../plans/appstore')
const OUT_DIR = path.resolve(HERE, '../src/content/legal')

// ── Fill these ──────────────────────────────────────────────────────────────
// Set to the Apple-registered legal entity / seller name (App Store Connect → Business).
// Confirmed 2026-07-06 = "Cu Dinh" (individual, Hanoi VN). If your full legal name on your ID
// (CCCD) is longer, use that instead — it must match the name Apple displays as the seller.
const LEGAL_NAME_EN = 'Cu Dinh'
const LEGAL_NAME_VI = 'Cự Đinh'
const EFFECTIVE_DATE = '2026-07-03'
const DOMAIN = 'https://mydeutschflow.com'
const SUPPORT_EMAIL = 'dinhhuycu0305@gmail.com'
// ────────────────────────────────────────────────────────────────────────────

const FILES = [
  { md: 'PRIVACY_POLICY.md', out: 'privacy.ts', constName: 'PRIVACY_MD' },
  { md: 'TERMS_OF_USE.md', out: 'terms.ts', constName: 'TERMS_MD' },
]

function fill(md) {
  return md
    .replace(/\[\[Legal name[^\]]*\]\]/g, LEGAL_NAME_EN)
    .replace(/\[\[Tên pháp lý[^\]]*\]\]/g, LEGAL_NAME_VI)
    .replace(/\[\[YYYY-MM-DD\]\]/g, EFFECTIVE_DATE)
    .replace(/\[\[https:\/\/your-domain\/privacy\]\]/g, `${DOMAIN}/privacy`)
    .replace(/\[\[privacy-policy-url\]\]/g, `${DOMAIN}/privacy`)
    .replace(/\[\[support@your-domain\]\]/g, SUPPORT_EMAIL)
    // Drop the authoring reminder line (contains a literal [[…]]) — not for the public page.
    .replace(/^>.*\[\[…\]\].*$\n?/gm, '')
}

for (const f of FILES) {
  const md = fs.readFileSync(path.join(SRC_DIR, f.md), 'utf8')
  const filled = fill(md)
  const leftover = filled.match(/\[\[[^\]]+\]\]/g)
  if (leftover) console.warn(`⚠️  ${f.out}: unresolved placeholders: ${[...new Set(leftover)].join(', ')}`)
  const banner =
    `// AUTO-GENERATED by scripts/gen-legal.mjs from plans/appstore/${f.md}. Do NOT edit by hand —\n` +
    `// edit the markdown template or the constants in gen-legal.mjs and re-run the script.\n` +
    `// Data-controller identity is currently the interim '${LEGAL_NAME_EN}' — replace with the\n` +
    `// registered legal name (Apple seller / tax) in gen-legal.mjs before App Store submission.\n`
  fs.writeFileSync(
    path.join(OUT_DIR, f.out),
    `${banner}export const ${f.constName} = ${JSON.stringify(filled)};\n`,
  )
  console.log(`✓ ${f.out}: ${filled.length} chars`)
}
